import json

with open("assets/data/vocabulary.json", "r", encoding="utf-8") as f:
    data = json.load(f)

common_words_data = [
    ("Time", "Tiempo", "/taɪm/",
     "Time flies when you're having fun.",
     "El tiempo vuela cuando te diviertes.",
     ["What time does the movie start?",
      "I don't have time to finish this today.",
      "By the time we arrived, the party was over."]),
    ("Year", "Año", "/jɪər/",
     "This year has been really challenging for all of us.",
     "Este año ha sido realmente desafiante para todos nosotros.",
     ["Next year I want to travel to Europe.",
      "Last year we bought our first house together.",
      "The school year starts in September."]),
    ("People", "Gente / Personas", "/ˈpiːpəl/",
     "People around the world celebrate different holidays.",
     "La gente de todo el mundo celebra diferentes fiestas.",
     ["Many people came to the concert last night.",
      "Some people prefer tea over coffee.",
      "The people who live here are very friendly."]),
    ("Way", "Forma / Manera / Camino", "/weɪ/",
     "There's always a way to solve any problem.",
     "Siempre hay una forma de resolver cualquier problema.",
     ["Can you show me the way to the station?",
      "She cooks in a very traditional way.",
      "By the way, did you see my keys anywhere?"]),
    ("Day", "Día", "/deɪ/",
     "Today is a beautiful day to go to the beach.",
     "Hoy es un día hermoso para ir a la playa.",
     ["Every day I wake up at 6 AM.",
      "We had such a great day at the museum.",
      "The other day I ran into an old friend."]),
    ("Man", "Hombre", "/mæn/",
     "The man standing by the door is my boss.",
     "El hombre de pie junto a la puerta es mi jefe.",
     ["A young man helped me carry my groceries.",
      "The man in the blue jacket is a doctor.",
      "He grew up to be a very honest man."]),
    ("Thing", "Cosa", "/θɪŋ/",
     "The best thing about holidays is the food.",
     "Lo mejor de las vacaciones es la comida.",
     ["Don't forget the most important thing of all.",
      "How do you turn this thing on?",
      "One thing leads to another, as they say."]),
    ("Woman", "Mujer", "/ˈwʊmən/",
     "The woman who won the prize gave a great speech.",
     "La mujer que ganó el premio dio un gran discurso.",
     ["A woman from the office called while you were out.",
      "She became the first woman president of the company.",
      "The woman sitting next to me on the plane was a nurse."]),
    ("Life", "Vida", "/laɪf/",
     "Life is full of beautiful surprises if you pay attention.",
     "La vida está llena de sorpresas hermosas si prestas atención.",
     ["She decided to start a new life in another country.",
      "My grandmother lived a long and happy life.",
      "Water is essential for all life on Earth."]),
    ("World", "Mundo", "/wɜːrld/",
     "The world is getting smaller thanks to the internet.",
     "El mundo se está volviendo más pequeño gracias a internet.",
     ["He wants to travel around the world someday.",
      "What in the world happened here last night?",
      "English is spoken all over the world."]),
    ("School", "Escuela", "/skuːl/",
     "I walk to school every morning with my friends.",
     "Camino a la escuela todas las mañanas con mis amigos.",
     ["Our school has a very good reputation.",
      "After school I usually go to the library.",
      "She's studying law at university school."]),
    ("State", "Estado / Situación", "/steɪt/",
     "The house was in terrible state after the storm.",
     "La casa estaba en un estado terrible después de la tormenta.",
     ["California is the most populated state in the US.",
      "Please state your name clearly for the record.",
      "He was in a state of shock after hearing the news."]),
    ("Family", "Familia", "/ˈfæməli/",
     "Family is the most important thing in my life.",
     "La familia es lo más importante en mi vida.",
     ["We're going to visit my family this weekend.",
      "Her family has lived here for three generations.",
      "I come from a very large family of seven children."]),
    ("Student", "Estudiante", "/ˈstuːdənt/",
     "Every student must pass the final exam to graduate.",
     "Cada estudiante debe aprobar el examen final para graduarse.",
     ["She was an excellent student in high school.",
      "The student asked a very intelligent question in class.",
      "He works as a part-time student at the restaurant."]),
    ("Country", "País", "/ˈkʌntri/",
     "This country is known for its beautiful landscapes.",
     "Este país es conocido por sus hermosos paisajes.",
     ["My parents came to this country when they were young.",
      "The country's economy is growing very fast.",
      "We visited four different countries on our trip."]),
    ("Problem", "Problema", "/ˈprɒbləm/",
     "Let's sit down and talk about this problem calmly.",
     "Sentémonos y hablemos de este problema con calma.",
     ["The main problem is lack of time, not money.",
      "No problem — I can help you fix it tomorrow.",
      "Every problem has a solution if you think hard enough."]),
    ("Part", "Parte", "/pɑːrt/",
     "The most difficult part of the job was the interview.",
     "La parte más difícil del trabajo fue la entrevista.",
     ["For the most part, I agree with what you're saying.",
      "Take part in the discussion if you have ideas.",
      "This is just a small part of the whole project."]),
    ("Place", "Lugar", "/pleɪs/",
     "This is my favorite place in the entire city.",
     "Este es mi lugar favorito de toda la ciudad.",
     ["Can you save me a place in the queue?",
      "They've changed so much — it's hard to recognize the place.",
      "First place goes to the young woman from Spain."]),
    ("Question", "Pregunta", "/ˈkwɛstʃən/",
     "Good question — I actually don't know the answer.",
     "Buena pregunta — de hecho no sé la respuesta.",
     ["If you have any question, just raise your hand.",
      "There's no question that he's the best candidate.",
      "The real question is whether we can afford this."]),
    ("Government", "Gobierno", "/ˈɡʌvərnmənt/",
     "The government announced new tax reforms yesterday.",
     "El gobierno anunció nuevas reformas tributarias ayer.",
     ["The government provides free healthcare for everyone.",
      "A new government was elected last month.",
      "Critics say the government should do more about climate change."]),
    ("Company", "Empresa / Compañía", "/ˈkʌmpəni/",
     "My brother works for a big technology company.",
     "Mi hermano trabaja para una gran empresa de tecnología.",
     ["The company just launched a brand new product.",
      "She's been with the same company for twenty years.",
      "I enjoy your company — let's do this again soon."]),
    ("System", "Sistema", "/ˈsɪstəm/",
     "The education system needs to be completely reformed.",
     "El sistema educativo necesita ser reformado por completo.",
     ["Our operating system crashed during the presentation.",
      "The human body has an amazing immune system.",
      "There's a new system in place for filing complaints."]),
    ("Program", "Programa", "/ˈproʊɡræm/",
     "Did you watch that new television program last night?",
     "¿Viste ese nuevo programa de televisión anoche?",
     ["She's writing a computer program for her thesis.",
      "The training program lasts about three months.",
      "According to the program, the concert starts at 8."]),
    ("Question", "Pregunta / Cuestión", "/ˈkwɛstʃən/",
     "The age of the universe is a fascinating scientific question.",
     "La edad del universo es una cuestión científica fascinante.",
     ["You should never question your own worth.",
      "It's only a question of time before they find out.",
      "Her honesty is beyond any question or doubt."]),
    ("Work", "Trabajo / Obra", "/wɜːrk/",
     "His latest work of art was sold for two million dollars.",
     "Su última obra de arte se vendió por dos millones de dólares.",
     ["I've got a lot of work to finish before Friday.",
      "She goes to work by bus every single morning.",
      "At the end of the day, teamwork really does work."]),
    ("Government", "Gobierno", "/ˈɡʌvərnmənt/",
     "The government released new guidelines about public health.",
     "El gobierno publicó nuevas directrices sobre salud pública.",
     ["The government building is on the main square.",
      "The government will raise taxes next fiscal year.",
      "The government denied the accusations in a press release."]),
    ("Number", "Número / Cantidad", "/ˈnʌmbər/",
     "A large number of people attended the outdoor festival.",
     "Una gran cantidad de personas asistieron al festival al aire libre.",
     ["Can you give me your phone number, please?",
      "The number of students has doubled since last year.",
      "Don't worry — your number is finally up."]),
    ("Night", "Noche", "/naɪt/",
     "We walked around the city all night without sleeping.",
     "Caminamos por toda la ciudad toda la noche sin dormir.",
     ["Good night, sweet dreams — see you tomorrow!",
      "Last night I had the most amazing dream ever.",
      "The city looks so beautiful at night with all the lights."]),
    ("Point", "Punto / Aspecto", "/pɔɪnt/",
     "She made some excellent points during the meeting.",
     "Ella hizo algunos puntos excelentes durante la reunión.",
     ["What's the point of complaining if we can't change it?",
      "From my point of view, it was the right decision.",
      "The train leaves at 4 o'clock — don't miss that point."]),
    ("Home", "Hogar / Casa", "/hoʊm/",
     "There's no place like home after a long trip.",
     "No hay lugar como el hogar después de un viaje largo.",
     ["I'm usually home by seven o'clock at night.",
      "Let's stay home tonight and watch a good movie.",
      "She left home when she was only eighteen years old."]),
    ("Water", "Agua", "/ˈwɒtər/",
     "Please give me a glass of water — I'm really thirsty.",
     "Por favor dame un vaso de agua — tengo mucha sed.",
     ["Hot water is not working in the building today.",
      "The water in the lake is perfectly clean and cold.",
      "Don't forget to water the plants while I'm away."]),
    ("Room", "Habitación / Sala / Espacio", "/ruːm/",
     "There's not enough room in this car for five people.",
     "No hay suficiente espacio en este coche para cinco personas.",
     ["Go to your room and do your homework right now.",
      "The waiting room was completely full of people.",
      "At least we have room to breathe in this new apartment."]),
    ("Mother", "Madre", "/ˈmʌðər/",
     "My mother taught me how to cook when I was little.",
     "Mi madre me enseñó a cocinar cuando era pequeño.",
     ["She became a mother for the first time at twenty-eight.",
      "My mother-in-law is coming to visit us next week.",
      "Mother Nature always finds a way to surprise us."]),
    ("Area", "Área / Zona", "/ˈɛriə/",
     "This area used to be a forest many years ago.",
     "Esta zona solía ser un bosque hace muchos años.",
     ["I'm looking for the residential area on the map.",
      "The main shopping area is just a few blocks from here.",
      "She works in the area of scientific research."]),
    ("Money", "Dinero", "/ˈmʌni/",
     "Money can't buy you happiness, but it helps.",
     "El dinero no puede comprarte la felicidad, pero ayuda.",
     ["Don't waste your money on things you don't need.",
      "He borrowed a large sum of money from his sister.",
      "How much money do you have in your bank account?"]),
    ("Story", "Historia / Cuento", "/ˈstɔːri/",
     "My grandfather tells the best stories from his childhood.",
     "Mi abuelo cuenta las mejores historias de su infancia.",
     ["The movie is based on a true story that happened in 1943.",
      "Can you read me a bedtime story tonight, please?",
      "But that's only one side of the story — we need more facts."]),
    ("Fact", "Hecho / Realidad", "/fækt/",
     "It's a well-known fact that smoking causes cancer.",
     "Es un hecho bien conocido que fumar causa cáncer.",
     ["Before you argue, check the facts carefully.",
      "The interesting fact is nobody knows who built it.",
      "In fact, I've never been there myself — only heard stories."]),
    ("Month", "Mes", "/mʌnθ/",
     "We're going on vacation next month to the mountains.",
     "Vamos de vacaciones el próximo mes a las montañas.",
     ["This month we have three birthdays in the family.",
      "I've been learning English for about six months.",
      "She moved here exactly one month ago today."]),
    ("Lot", "Lote / Mucho / Suerte", "/lɒt/",
     "Thanks a lot for helping me move into the new house.",
     "Muchas gracias por ayudarme a mudarme a la casa nueva.",
     ["He won the lottery — that's quite a lot of money!",
      "We have a lot to discuss in today's meeting.",
      "The parking lot is completely full — try the next one."]),
    ("Right", "Derecho / Correcto", "/raɪt/",
     "Everyone has the right to express their own opinion freely.",
     "Todos tienen el derecho de expresar su propia opinión libremente.",
     ["You were absolutely right about everything you said.",
      "Turn right at the next traffic light, please.",
      "Is that the right way to spell this word, teacher?"]),
    ("Study", "Estudio", "/ˈstʌdi/",
     "A recent study shows that walking improves memory.",
     "Un estudio reciente muestra que caminar mejora la memoria.",
     ["I need to study for my final exam all weekend.",
      "She went to London to study art and architecture.",
      "The study of history teaches us valuable lessons."]),
    ("Book", "Libro", "/bʊk/",
     "I just finished reading an amazing book about ancient Egypt.",
     "Acabo de terminar de leer un libro asombroso sobre el antiguo Egipto.",
     ["Can you recommend a good book for my vacation?",
      "I'd like to book a table for two at 8 PM, please.",
      "In my book, honesty always comes first — always."]),
    ("Eye", "Ojo", "/aɪ/",
     "She looked me straight in the eye and told me the truth.",
     "Ella me miró directamente a los ojos y me dijo la verdad.",
     ["Keep an eye on my suitcase while I buy the tickets.",
      "The view from the top was a real feast for the eyes.",
      "My grandmother has beautiful blue eyes like the ocean."]),
    ("Job", "Trabajo / Empleo", "/dʒɒb/",
     "Good job! You passed the exam with the highest score.",
     "¡Buen trabajo! Pasaste el examen con la puntuación más alta.",
     ["He got a really good job at an international company.",
      "It's my job to make sure everything runs smoothly here.",
      "Changing jobs can be both scary and exciting at the same time."]),
    ("Word", "Palabra", "/wɜːrd/",
     "I give you my word — I'll never tell anyone your secret.",
     "Te doy mi palabra — nunca le contaré a nadie tu secreto.",
     ["What does this word mean in this context?",
      "A word of caution — don't trust everything you read.",
      "In other words, we'll have to start all over again."]),
    ("Business", "Negocio / Empresa", "/ˈbɪznəs/",
     "My dream is to start my own business selling handmade jewelry.",
     "Mi sueño es montar mi propio negocio vendiendo joyas hechas a mano.",
     ["Business is going really well this quarter.",
      "None of your business — this is a private conversation.",
      "Let's get down to business and stop wasting time."]),
    ("Issue", "Asunto / Problema", "/ˈɪʃuː/",
     "Climate change is the biggest issue of our generation.",
     "El cambio climático es el mayor asunto de nuestra generación.",
     ["The new government issued a statement this morning.",
      "The latest issue of the magazine comes out tomorrow.",
      "Money is not the issue — it's about trust and respect."]),
    ("Side", "Lado / Banda", "/saɪd/",
     "There are always two sides to every story, you know.",
     "Siempre hay dos lados para cada historia, ¿sabes?",
     ["He always takes his brother's side in every argument.",
      "The car was badly damaged on the left side.",
      "On the bright side, we still have enough time to fix it."]),
    ("Kind", "Tipo / Clase / Amable", "/kaɪnd/",
     "Thank you — that was very kind of you to help me.",
     "Gracias — fue muy amable de tu parte ayudarme.",
     ["What kind of music do you usually listen to?",
      "He's one of the kindest people I've ever met.",
      "This is a new kind of technology nobody has seen before."]),
    ("Quality", "Calidad / Cualidad", "/ˈkwɒləti/",
     "Always choose quality over quantity when buying clothes.",
     "Elige siempre la calidad sobre la cantidad al comprar ropa.",
     ["The food quality at that restaurant is outstanding.",
      "Patience is a quality not many people have these days.",
      "They have improved the quality of their service a lot."]),
    ("Child", "Niño / Niña / Hijo", "/tʃaɪld/",
     "Every child deserves love, attention, and proper education.",
     "Cada niño merece amor, atención y educación adecuada.",
     ["Their first child was born last winter in December.",
      "The child drew a beautiful picture of a rainbow.",
      "When I was a child I wanted to become an astronaut."]),
    ("Service", "Servicio", "/ˈsɜːrvɪs/",
     "The customer service at this hotel is absolutely amazing.",
     "El servicio al cliente en este hotel es absolutamente increíble.",
     ["Breakfast is included in the room service package.",
      "The bus service runs every 15 minutes during rush hour.",
      "He was awarded for his many years of public service."]),
    ("Friend", "Amigo / Amiga", "/frɛnd/",
     "She's been my best friend since we were in kindergarten.",
     "Ella ha sido mi mejor amiga desde que estábamos en el jardín de infancia.",
     ["A friend in need is a friend indeed, as the proverb says.",
      "We're going to meet some old friends for dinner tonight.",
      "He's more than a colleague — he's a true friend to me."]),
    ("Heart", "Corazón", "/hɑːrt/",
     "Follow your heart and you'll never regret your decision.",
     "Sigue tu corazón y nunca te arrepentirás de tu decisión.",
     ["She thanked him from the bottom of her heart.",
      "The poor child had a heart condition since birth.",
      "Berlin is the heart and soul of Germany in many ways."]),
    ("End", "Fin / Final", "/ɛnd/",
     "In the end, honesty always wins over deception and lies.",
     "Al final, la honestidad siempre gana sobre el engaño y las mentiras.",
     ["At the end of the street you'll see a big park.",
      "The movie had a very sad ending that made me cry.",
      "How does this story end? Please don't leave me hanging."]),
    ("Law", "Ley", "/lɔː/",
     "Everyone is equal before the law — regardless of their position.",
     "Todos son iguales ante la ley, independientemente de su posición.",
     ["Ignorance of the law is no excuse for breaking it.",
      "She's currently studying law at Harvard University.",
      "By law, you must wear a seatbelt while driving."]),
    ("Name", "Nombre / Nombre de pila", "/neɪm/",
     "What's the name of that beautiful song you were singing?",
     "¿Cómo se llama esa canción tan hermosa que estabas cantando?",
     ["Please write your full name and address on this form.",
      "She was named after her grandmother, who she never met.",
      "In the name of love, people do incredible things."]),
    ("House", "Casa", "/haʊs/",
     "We're planning to buy a small house by the lake next year.",
     "Estamos planeando comprar una casa pequeña junto al lago el próximo año.",
     ["Our house was built in 1920 by my great-grandfather.",
      "Let's meet at my house after work for some coffee.",
      "The White House is the official residence of the US president."]),
    ("Head", "Cabeza / Jefe", "/hɛd/",
     "She was appointed as the new head of the department last week.",
     "Ella fue nombrada la nueva jefa del departamento la semana pasada.",
     ["Use your head and think before making a decision this big.",
      "My head hurts really badly today — I think I'm getting sick.",
      "He nodded his head in complete agreement with what I said."]),
    ("Stand", "Puesto / Postura", "/stænd/",
     "Nobody knew where she really stood on that particular issue.",
     "Nadie sabía cuál era realmente su postura sobre ese tema en particular.",
     ["Please stand up when the judge enters the courtroom.",
      "I can't stand that loud music — please turn it down.",
      "The fruit stand on the corner sells the freshest apples in town."]),
    ("Current", "Actual / Corriente", "/ˈkɜːrənt/",
     "According to current statistics, unemployment is decreasing.",
     "Según las estadísticas actuales, el desempleo está disminuyendo.",
     ["The current situation is critical but not completely hopeless.",
      "Be careful — the water current here is extremely powerful.",
      "What is the current exchange rate between euros and dollars?"]),
    ("Game", "Juego / Partido", "/ɡeɪm/",
     "Last night's football game was absolutely thrilling to watch.",
     "El partido de fútbol de anoche fue absolutamente emocionante de ver.",
     ["Let's play a board game together after dinner tonight.",
      "It's all part of the game — you'll learn to handle it.",
      "She's been playing video games since she was a small child."]),
    ("Line", "Línea / Fila", "/laɪn/",
     "Please stand in line and wait patiently for your turn.",
     "Por favor, hagan fila y esperen pacientemente su turno.",
     ["That was the funniest line in the entire comedy movie.",
      "Draw a straight line from point A to point B here.",
      "We had to wait in line for two hours at the airport."]),
    ("City", "Ciudad", "/ˈsɪti/",
     "New York City is one of the most exciting places in the world.",
     "La ciudad de Nueva York es uno de los lugares más emocionantes del mundo.",
     ["Mexico City is the largest city in the Spanish-speaking world.",
      "They moved from the countryside to the city last year.",
      "The city center is full of historic buildings and monuments."]),
    ("Community", "Comunidad", "/kəˈmjuːnəti/",
     "The whole community came together to help after the earthquake.",
     "Toda la comunidad se unió para ayudar después del terremoto.",
     ["She's very active in the local community volunteer programs.",
      "There's a strong sense of community in this small town.",
      "The online community helped raise money for the family in need."]),
    ("Name", "Nombre / Apellido", "/neɪm/",
     "Please call me by my first name — there's no need to be formal.",
     "Por favor llámame por mi nombre de pila — no hay necesidad de ser formal.",
     ["He made a name for himself as a talented young painter.",
      "The restaurant got its name from the owner's beloved grandmother.",
      "I can never remember the names of all the people I meet."]),
    ("President", "Presidente", "/ˈprɛzɪdənt/",
     "The president will address the nation on television tonight.",
     "El presidente se dirigirá a la nación por televisión esta noche.",
     ["She was elected president of the student council last semester.",
      "The president met with other world leaders at the summit.",
      "George Washington was the first president of the United States."]),
    ("Team", "Equipo", "/tiːm/",
     "Our team won the championship for the third consecutive year.",
     "Nuestro equipo ganó el campeonato por tercer año consecutivo.",
     ["We're looking for new members to join our football team.",
      "Team spirit is very important for achieving common goals.",
      "She works as part of a research team at the university."]),
    ("Minute", "Minuto", "/ˈmɪnɪt/",
     "Wait just a minute — I'm almost ready to leave the house.",
     "Espera solo un minuto — casi estoy lista para salir de casa.",
     ["I'll be there in five minutes — please don't leave without me.",
      "Wait a minute — that can't be right. Are you sure?",
      "She studied the document for twenty minutes before answering."]),
    ("Idea", "Idea", "/aɪˈdiːə/",
     "That's the most brilliant idea I've heard in a very long time.",
     "Esa es la idea más brillante que he escuchado en mucho tiempo.",
     ["I have no idea where I put my wallet — can you help me look?",
      "Great minds think alike — I had the very same idea myself!",
      "Don't fall in love with the first idea that comes to your head."]),
    ("Car", "Coche / Auto", "/kɑːr/",
     "We drove all day by car until we reached the beautiful coast.",
     "Condujimos todo el día en coche hasta llegar a la hermosa costa.",
     ["My car broke down on the highway in the middle of nowhere.",
      "He bought a brand-new electric car last month.",
      "There's a car waiting for you outside whenever you're ready."]),
    ("Level", "Nivel / Nivelado", "/ˈlɛvəl/",
     "The noise level in the office was starting to affect my concentration.",
     "El nivel de ruido en la oficina estaba empezando a afectar mi concentración.",
     ["This game is very hard — try the beginner level first.",
      "She reached a very high level of fluency in just one year.",
      "We need to have a level playing field for all competitors."]),
    ("Opportunity", "Oportunidad", "/ˌɒpərˈtjuːnəti/",
     "Don't miss this unique opportunity to learn from the best.",
     "No pierdas esta oportunidad única de aprender de los mejores.",
     ["This job is a wonderful opportunity to grow professionally.",
      "I'd like to take this opportunity to thank you all for coming.",
      "Life is full of opportunities for those who are prepared."]),
    ("Organization", "Organización", "/ˌɔːrɡənəˈzeɪʃən/",
     "She works for a non-profit organization that helps homeless people.",
     "Ella trabaja para una organización sin fines de lucro que ayuda a las personas sin hogar.",
     ["The organization of the event was truly impressive.",
      "He joined a human rights organization after graduating.",
      "A good organization is the key to running any successful business."]),
    ("Information", "Información", "/ˌɪnfərˈmeɪʃən/",
     "Could you please give me some information about your courses?",
     "¿Podría darme algo de información sobre sus cursos, por favor?",
     ["All the information you need is on the official website.",
      "For your information, we're closed on Mondays.",
      "Sensitive information must be protected at all times."]),
    ("Age", "Edad / Época", "/eɪdʒ/",
     "She started playing the piano at the tender age of only four.",
     "Ella empezó a tocar el piano a la tierna edad de solo cuatro años.",
     ["In this day and age, technology is everywhere around us.",
      "You can do anything at any age if you really put your mind to it.",
      "What's the legal age for driving a car in your country?"]),
    ("Date", "Fecha / Cita", "/deɪt/",
     "What's today's date? I completely forgot about the deadline.",
     "¿Cuál es la fecha de hoy? Olvidé por completo la fecha límite.",
     ["We went on our first date exactly ten years ago today.",
      "Please sign and write the date at the bottom of the contract.",
      "Are we still on for our dinner date tomorrow night at seven?"]),
    ("Result", "Resultado", "/rɪˈzʌlt/",
     "The exam results will be posted on the notice board on Friday.",
     "Los resultados del examen se publicarán en el tablón de anuncios el viernes.",
     ["As a result of the heavy rain, all flights were canceled.",
      "She worked very hard and saw great results very quickly.",
      "The results of the research were published in a scientific journal."]),
    ("Change", "Cambio / Cambio", "/tʃeɪndʒ/",
     "Sometimes change is necessary for personal growth and happiness.",
     "A veces el cambio es necesario para el crecimiento personal y la felicidad.",
     ["Here's your change — keep the receipt just in case.",
      "You have to change trains at the next station, then take line 3.",
      "Small changes in your routine can make a huge difference."]),
    ("Morning", "Mañana / Madrugada", "/ˈmɔːrnɪŋ/",
     "Every morning I drink a cup of coffee before doing anything else.",
     "Todas las mañanas bebo una taza de café antes de hacer cualquier otra cosa.",
     ["Good morning! Did you sleep well last night, darling?",
      "We watched the sunrise early yesterday morning at the beach.",
      "On Sunday mornings we usually go out for a big breakfast."]),
    ("Reason", "Razón / Motivo", "/ˈriːzən/",
     "There must be a reason why she didn't show up to the party.",
     "Debe haber una razón por la que ella no apareció en la fiesta.",
     ["Please give me one good reason to believe you this time.",
      "With reason, they were extremely upset about the whole situation.",
      "I couldn't reason with him — he was too stubborn to listen."]),
    ("Research", "Investigación", "/ˈriːsɜːrtʃ/",
     "Scientists do extensive research before making any public claim.",
     "Los científicos hacen investigaciones extensas antes de hacer cualquier afirmación pública.",
     ["She's currently doing cancer research at a famous hospital.",
      "Further research is needed to confirm these early findings.",
      "Always research before making any big financial decision."]),
    ("Street", "Calle", "/striːt/",
     "There's a lovely little café on this street — let's go in.",
     "Hay un pequeño café encantador en esta calle — entremos.",
     ["Don't play in the street — it's very dangerous with cars passing.",
      "Wall Street is the financial center of the whole world.",
      "They walked down the street holding hands and talking happily."]),
    ("Market", "Mercado / Mercado", "/ˈmɑːrkɪt/",
     "We buy fresh vegetables at the local market every Saturday morning.",
     "Compramos verduras frescas en el mercado local todos los sábados por la mañana.",
     ["The stock market crashed dramatically last Tuesday afternoon.",
      "Our target market is mainly young professionals in the city.",
      "They're bringing a new product to the market next spring."]),
    ("Guide", "Guía / Guiar", "/ɡaɪd/",
     "Our tour guide knew everything about the history of this old castle.",
     "Nuestro guía turístico sabía todo sobre la historia de este viejo castillo.",
     ["Let these mistakes guide you and help you become better.",
      "She wrote a complete guide to healthy eating on a budget.",
      "The lighthouse guides ships safely into the harbor at night."]),
    ("Experience", "Experiencia", "/ɪkˈspɪəriəns/",
     "Working abroad was the most rewarding experience of my entire life.",
     "Trabajar en el extranjero fue la experiencia más gratificante de toda mi vida.",
     ["Do you have any previous experience working with children?",
      "I experienced a strange feeling when I entered the old house.",
      "He has over twenty years of experience in the tech industry."]),
    ("Project", "Proyecto", "/ˈprɒdʒɛkt/",
     "We're currently working on a very exciting project for next summer.",
     "Actualmente estamos trabajando en un proyecto muy emocionante para el próximo verano.",
     ["The project was completed ahead of schedule and under budget.",
      "She's in charge of managing the entire marketing project.",
      "Our final school project required us to build a small robot."]),
    ("Chance", "Oportunidad / Posibilidad", "/tʃæns/",
     "This is your last chance — you better think carefully before answering.",
     "Esta es tu última oportunidad — mejor piensa cuidadosamente antes de responder.",
     ["There's a good chance of rain tonight according to the forecast.",
      "We ran into each other completely by chance at the airport.",
      "I never miss a chance to spend time with my grandparents."]),
    ("Environment", "Medio ambiente / Entorno", "/ɪnˈvaɪrənmənt/",
     "We should all try to protect the environment for future generations.",
     "Todos deberíamos intentar proteger el medio ambiente para las generaciones futuras.",
     ["The work environment in this company is really positive and friendly.",
      "Children need a safe environment to grow and develop properly.",
      "Small changes in our daily habits can really help the environment."]),
    ("Resource", "Recurso", "/ˈriːsɔːrs/",
     "Water is our most precious natural resource on this planet.",
     "El agua es nuestro recurso natural más preciado en este planeta.",
     ["This library is an excellent resource for students and researchers.",
      "Human resources are the heart and soul of every great company.",
      "We must learn to use our limited resources more efficiently."]),
    ("History", "Historia", "/ˈhɪstəri/",
     "The history of ancient Egypt has always fascinated me deeply.",
     "La historia del antiguo Egipto siempre me ha fascinado profundamente.",
     ["Our history teacher makes every lesson really interesting and fun.",
      "Those two families have a long history of conflict and rivalry.",
      "Throughout history, many great empires have risen and fallen."]),
    ("Music", "Música", "/ˈmjuːzɪk/",
     "Listening to good music always improves my mood immediately.",
     "Escuchar buena música siempre mejora mi estado de ánimo de inmediato.",
     ["She studied classical music at the conservatory for many years.",
      "What kind of music do you enjoy listening to while working?",
      "Music is the universal language that connects all of humanity."]),
    ("Road", "Carretera / Camino", "/roʊd/",
     "The road to success is never straight — it has many curves.",
     "El camino hacia el éxito nunca es recto — tiene muchas curvas.",
     ["We took the scenic road along the coast instead of the highway.",
      "There was a terrible accident on the main road this morning.",
      "All roads lead to Rome — or so the old proverb says."]),
    ("Example", "Ejemplo", "/ɪɡˈzæmpəl/",
     "Parents should always give their children a good example to follow.",
     "Los padres siempre deben dar a sus hijos un buen ejemplo a seguir.",
     ["Let me give you a simple example to explain this concept.",
      "She followed the example of her hero and became a doctor.",
      "For example, you could start by saving just ten dollars a week."]),
    ("Education", "Educación", "/ˌɛdʒuˈkeɪʃən/",
     "Education is the most powerful weapon to change the whole world.",
     "La educación es el arma más poderosa para cambiar todo el mundo.",
     ["She received an excellent education at a very prestigious university.",
      "Every child has the right to free education in our country.",
      "Education opens many doors that would otherwise stay closed."]),
    ("Community", "Comunidad / Vecindario", "/kəˈmjuːnəti/",
     "The community garden is open to everyone who lives in this area.",
     "El jardín comunitario está abierto a todos los que viven en esta zona.",
     ["The whole community came out to celebrate the annual festival.",
      "Community service is a requirement for graduation from high school.",
      "He's well known and respected by everyone in the local community."]),
    ("Relationship", "Relación", "/rɪˈleɪʃənʃɪp/",
     "Honesty is the foundation of any strong and healthy relationship.",
     "La honestidad es la base de cualquier relación fuerte y saludable.",
     ["The relationship between the two countries has improved recently.",
      "Their working relationship eventually turned into true friendship.",
      "Communication is key in every relationship — personal or professional."]),
    ("Position", "Posición / Puesto", "/pəˈzɪʃən/",
     "From my position at the window, I could see everything clearly.",
     "Desde mi posición en la ventana, podía ver todo claramente.",
     ["She applied for the position of sales manager at the firm.",
      "What is your position on this controversial political issue?",
      "The army was in position before dawn — ready for attack."]),
    ("Trade", "Comercio / Intercambio", "/treɪd/",
     "International trade has increased dramatically in the last few decades.",
     "El comercio internacional ha aumentado dramáticamente en las últimas décadas.",
     ["He works in the trade department of a large multinational company.",
      "I'll trade you my apple for your orange — what do you say?",
      "Fair trade products guarantee better wages for the workers."]),
    ("Food", "Comida / Alimento", "/fuːd/",
     "We tried the most amazing traditional food at the small village.",
     "Probamos la comida tradicional más asombrosa en el pequeño pueblo.",
     ["Fast food is convenient but not very healthy to eat every day.",
      "Whole foods provide more nutrients than processed ones.",
      "The food at the wedding reception was absolutely delicious."]),
    ("Theory", "Teoría", "/ˈθɪəri/",
     "In theory, the plan should work perfectly — but let's test it first.",
     "En teoría, el plan debería funcionar perfectamente — pero vamos a probarlo primero.",
     ["Einstein's theory of relativity changed modern physics forever.",
      "There are many different theories about the origin of the universe.",
      "Your theory sounds interesting but where is the concrete evidence?"]),
    ("Law", "Ley / Derecho", "/lɔː/",
     "It's against the law to park in front of a fire hydrant anywhere.",
     "Es ilegal estacionar frente a una boca de incendios en cualquier lugar.",
     ["She's been practicing corporate law for more than fifteen years.",
      "New laws were passed to protect the rights of domestic workers.",
      "The Murphy Law says: if something can go wrong, it will."]),
    ("Building", "Edificio / Construcción", "/ˈbɪldɪŋ/",
     "That building over there is the tallest in the entire country.",
     "Ese edificio de allá es el más alto de todo el país.",
     ["The construction of the new building will start next month.",
      "She works on the 17th floor of that modern glass building.",
      "Muscle building requires both exercise and proper nutrition."]),
    ("Material", "Material", "/məˈtɪriəl/",
     "What kind of material is this sweater made of — it feels so soft.",
     "¿De qué tipo de material está hecho este suéter — se siente tan suave.",
     ["We need to buy all the building materials before starting.",
      "Raw materials are imported from many different countries.",
      "You'll find all the study materials on the professor's website."]),
    ("Population", "Población", "/ˌpɒpjʊˈleɪʃən/",
     "The population of the world has reached eight billion people.",
     "La población del mundo ha alcanzado los ocho mil millones de personas.",
     ["The population of this small town is only around three thousand.",
      "Overpopulation is one of the biggest challenges we face today.",
      "The native population was almost wiped out by European diseases."]),
    ("Economy", "Economía", "/ɪˈkɒnəmi/",
     "The country's economy has been growing steadily for the past five years.",
     "La economía del país ha estado creciendo constantemente durante los últimos cinco años.",
     ["The global economy was deeply affected by the recent pandemic.",
      "She studied economy at university and now works at a bank.",
      "Tourism plays a major role in the local economy of this region."]),
    ("Moment", "Momento", "/ˈmoʊmənt/",
     "This is the perfect moment to tell everyone about our engagement.",
     "Este es el momento perfecto para contarles a todos sobre nuestro compromiso.",
     ["For a moment I thought she was going to say no — I was so nervous.",
      "Could you wait a moment? I need to grab my jacket and keys.",
      "Some moments in life are worth remembering forever — cherish them."]),
    ("Agreement", "Acuerdo / Convenio", "/əˈɡriːmənt/",
     "After many hours of negotiation, they finally reached an agreement.",
     "Después de muchas horas de negociación, finalmente llegaron a un acuerdo.",
     ["Both parties signed the agreement this morning in the boardroom.",
      "We have a gentleman's agreement — no contract needed between us.",
      "The divorce agreement included shared custody of the three children."]),
    ("Hospital", "Hospital", "/ˈhɒspɪtəl/",
     "She had to go to the hospital after she fell down the stairs.",
     "Ella tuvo que ir al hospital después de caerse por las escaleras.",
     ["The new hospital has the most modern equipment in the region.",
      "He spent two weeks in the hospital recovering from surgery.",
      "The hospital staff was extremely kind and caring throughout my stay."]),
    ("Painting", "Pintura / Cuadro", "/ˈpeɪntɪŋ/",
     "That beautiful painting on the wall was done by my older sister.",
     "Esa hermosa pintura de la pared fue hecha por mi hermana mayor.",
     ["Painting is one of my favorite hobbies when I have free time.",
      "They bought an original painting at an auction for a fortune.",
      "The painting of the old house reminds me of my grandmother's home."]),
    ("Language", "Idioma / Lengua", "/ˈlæŋɡwɪdʒ/",
     "Learning a new language opens your mind to other cultures.",
     "Aprender un nuevo idioma abre tu mente a otras culturas.",
     ["English has become the international language of business.",
      "Body language can tell you more than words sometimes.",
      "She speaks four languages fluently: Spanish, English, French and Italian."]),
]

verb_tenses_data = [
    ("Present Simple", "Presente Simple",
     "Subject + Verb (-s for he/she/it)",
     "/ˈprɛzənt ˈsɪmpəl/",
     "I drink coffee every single morning before work.",
     "Bebo café todas las mañanas antes del trabajo.",
     ["She works in a hospital as a pediatric nurse.",
      "The sun rises in the east and sets in the west.",
      "They usually travel to Europe once every two years."]),
    ("Present Continuous", "Presente Continuo",
     "Subject + am/is/are + Verb-ing",
     "/ˈprɛzənt kənˈtɪnjuəs/",
     "I am reading a very interesting book right now.",
     "Estoy leyendo un libro muy interesante ahora mismo.",
     ["She is cooking dinner in the kitchen for her family.",
      "We are building our own house in the countryside.",
      "They are currently discussing the new marketing strategy."]),
    ("Present Perfect", "Presente Perfecto",
     "Subject + have/has + Past Participle",
     "/ˈprɛzənt ˈpɜːrfɪkt/",
     "I have visited that beautiful country three times already.",
     "He visitado ese hermoso país tres veces ya.",
     ["She has already finished her master's degree thesis.",
      "We have lived in this neighborhood for fifteen years.",
      "He has never tried sushi in his entire life — would you believe it?"]),
    ("Present Perfect Continuous", "Presente Perfecto Continuo",
     "Subject + have/has + been + Verb-ing",
     "/ˈprɛzənt ˈpɜːrfɪkt kənˈtɪnjuəs/",
     "I have been studying English for almost six years now.",
     "He estado estudiando inglés durante casi seis años ya.",
     ["She has been working since six in the morning today.",
      "They have been building that bridge for over three years.",
      "We have been waiting here for more than an hour and a half."]),
    ("Past Simple", "Pasado Simple",
     "Subject + Past Verb",
     "/pæst ˈsɪmpəl/",
     "I went to Paris with my family two summers ago.",
     "Fui a París con mi familia hace dos veranos.",
     ["She bought a new laptop for work last Friday afternoon.",
      "We saw a very sad movie at the cinema yesterday evening.",
      "They lived in Japan from 2015 until very recently."]),
    ("Past Continuous", "Pasado Continuo",
     "Subject + was/were + Verb-ing",
     "/pæst kənˈtɪnjuəs/",
     "I was taking a shower when the phone suddenly rang.",
     "Estaba dándome una ducha cuando el teléfono sonó de repente.",
     ["She was studying while her brother was playing video games.",
      "They were walking in the park when it started to rain heavily.",
      "We were having a lovely dinner when the power went out suddenly."]),
    ("Past Perfect", "Pasado Perfecto",
     "Subject + had + Past Participle",
     "/pæst ˈpɜːrfɪkt/",
     "I had already eaten dinner when my friends arrived at my house.",
     "Ya había cenado cuando mis amigos llegaron a mi casa.",
     ["She had never tasted such delicious food before her trip to Italy.",
      "They had finished the project a week before the actual deadline.",
      "We realized we had been to that same place ten years earlier."]),
    ("Past Perfect Continuous", "Pasado Perfecto Continuo",
     "Subject + had + been + Verb-ing",
     "/pæst ˈpɜːrfɪkt kənˈtɪnjuəs/",
     "I had been working there for five years when they finally promoted me.",
     "Había estado trabajando allí durante cinco años cuando finalmente me ascendieron.",
     ["She had been waiting for over an hour when the taxi finally showed up.",
      "They had been traveling for twenty hours before they finally reached home.",
      "We had been searching for the keys for an hour when we found them."]),
    ("Future with Will", "Futuro con Will",
     "Subject + will + Verb",
     "/ˈfjuːtʃər wɪð wɪl/",
     "I will call you as soon as I arrive at the airport tomorrow.",
     "Te llamaré en cuanto llegue al aeropuerto mañana.",
     ["She will probably be late because of all the traffic tonight.",
      "Don't worry — I will help you finish the report after lunch.",
      "They will announce the winner of the contest in five minutes."]),
    ("Be Going To", "Futuro con Going To",
     "Subject + am/is/are + going to + Verb",
     "/bi ˈɡoʊɪŋ tuː/",
     "I am going to learn how to play the guitar next year.",
     "Voy a aprender a tocar la guitarra el próximo año.",
     ["She is going to have a baby in about three months.",
      "We are going to move to a bigger apartment next summer.",
      "They are going to open a new restaurant downtown very soon."]),
    ("Future Continuous", "Futuro Continuo",
     "Subject + will + be + Verb-ing",
     "/ˈfjuːtʃər kənˈtɪnjuəs/",
     "This time tomorrow I will be lying on a beach in Hawaii.",
     "A estas horas mañana estaré tirado en una playa en Hawái.",
     ["She will be giving an important presentation at ten o'clock.",
      "We will be driving through the mountains all day Saturday.",
      "This time next year they will be living in their brand new house."]),
    ("Future Perfect", "Futuro Perfecto",
     "Subject + will + have + Past Participle",
     "/ˈfjuːtʃər ˈpɜːrfɪkt/",
     "By the end of this year I will have finished my university degree.",
     "Para finales de este año habré terminado mi carrera universitaria.",
     ["By next month she will have worked here for exactly ten years.",
      "When you arrive, we will have already prepared everything for you.",
      "By 2030 they will have completed the entire construction project."]),
]

common_cards = []
for i, (wen, wes, pron, ex, exes, extras) in enumerate(common_words_data, 1):
    common_cards.append({
        "id": f"cw_{i}",
        "wordEn": wen,
        "wordEs": wes,
        "pronunciation": pron,
        "example": ex,
        "exampleEs": exes,
        "extraExamples": extras
    })

verb_tense_cards = []
for i, (wen, wes, struct, pron, ex, exes, extras) in enumerate(verb_tenses_data, 1):
    verb_tense_cards.append({
        "id": f"vt_{i}",
        "wordEn": wen,
        "wordEs": wes,
        "pronunciation": pron,
        "example": ex,
        "exampleEs": exes,
        "extraExamples": extras,
        "structure": struct
    })

category_common = {
    "id": "common_words",
    "name": "Common Words",
    "nameEs": "Palabras comunes",
    "icon": "📘",
    "color": "#66BB6A",
    "cards": common_cards
}

category_tenses = {
    "id": "verb_tenses",
    "name": "Verb Tenses",
    "nameEs": "Tiempos verbales",
    "icon": "⏱️",
    "color": "#AB47BC",
    "cards": verb_tense_cards
}

data["categories"].append(category_common)
data["categories"].append(category_tenses)

with open("assets/data/vocabulary.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"✅ Añadidas {len(common_cards)} tarjetas en categoría 'common_words'")
print(f"✅ Añadidas {len(verb_tense_cards)} tarjetas en categoría 'verb_tenses'")
print(f"✅ Total categorías ahora: {len(data['categories'])}")
