import json

with open("assets/data/vocabulary.json", "r", encoding="utf-8") as f:
    data = json.load(f)

data["categories"] = [c for c in data["categories"] if c["id"] not in ("common_words", "verb_tenses")]

harder_common_words = [
    ("Acknowledge", "Reconocer / Agradecer", "/əkˈnɒlɪdʒ/",
     "She refused to acknowledge her mistake in front of everyone.",
     "Ella se negó a reconocer su error frente a todos.",
     ["He acknowledged the applause with a small bow of his head.",
      "You must acknowledge that not everyone shares your point of view.",
      "The company acknowledged the delay and offered a full refund."]),
    ("Acquire", "Adquirir / Conseguir", "/əˈkwaɪər/",
     "He managed to acquire a rare first edition at the old bookstore.",
     "Él logró adquirir una rara primera edición en la vieja librería.",
     ["Young children acquire language skills at an astonishing speed.",
      "She acquired a taste for classical music from her grandfather.",
      "Museums compete to acquire the most important works of art."]),
    ("Ambiguous", "Ambiguo / Vago", "/æmˈbɪɡjuəs/",
     "His answer was deliberately ambiguous, leaving us all confused.",
     "Su respuesta fue deliberadamente ambigua, dejándonos a todos confundidos.",
     ["The contract language is ambiguous and could be interpreted two ways.",
      "She gave me an ambiguous smile that I couldn't really decipher.",
      "Avoid ambiguous statements when giving official press interviews."]),
    ("Analyze", "Analizar", "/ˈænəlaɪz/",
     "Scientists analyzed the data to find a hidden statistical pattern.",
     "Los científicos analizaron los datos para encontrar un patrón estadístico oculto.",
     ["We need to analyze the root cause of this recurring problem.",
      "The detective analyzed every clue at the crime scene carefully.",
      "Literature students learn to analyze poems and novels in depth."]),
    ("Anticipate", "Anticipar / Prever", "/ænˈtɪsɪpeɪt/",
     "We didn't anticipate such an overwhelming public reaction to the news.",
     "No anticipamos una reacción pública tan abrumadora ante la noticia.",
     ["Good generals always anticipate their enemy's next military move.",
      "She anticipated his needs even before he could express them.",
      "Investors anticipate another interest rate cut next month."]),
    ("Apparent", "Aparente / Evidente", "/əˈpærənt/",
     "It was apparent from her face that something terrible had happened.",
     "Era evidente por su rostro que algo terrible había sucedido.",
     ["The full extent of the damage only became apparent a week later.",
      "In spite of his apparent indifference, he cared deeply about her.",
      "There are three apparent advantages to this new approach we proposed."]),
    ("Appropriate", "Apropiado / Adecuado", "/əˈproʊpriət/",
     "Jeans are not appropriate attire for such a formal business meeting.",
     "Los vaqueros no son vestimenta apropiada para una reunión de negocios tan formal.",
     ["Please select the most appropriate answer from the four given options.",
      "An apology would be appropriate after such a disrespectful comment.",
      "They will take appropriate legal action against anyone infringing copyright."]),
    ("Assumption", "Suposición / Presunción", "/əˈsʌmpʃən/",
     "Your whole argument rests on a completely false assumption about human nature.",
     "Todo tu argumento se basa en una suposición completamente falsa sobre la naturaleza humana.",
     ["We are working on the assumption that interest rates will remain stable.",
      "Never make assumptions without first checking the actual facts.",
      "His silent assumption was that someone else would always clean the mess."]),
    ("Attempt", "Intento / Tentativa", "/əˈtɛmpt/",
     "It was a brave attempt even though it ultimately failed completely.",
     "Fue un intento valiente a pesar de que finalmente fracasó por completo.",
     ["This is my third attempt to pass the notoriously difficult exam.",
      "They made no attempt to escape and surrendered peacefully to police.",
      "Her first attempt at baking bread was surprisingly actually quite good."]),
    ("Attribute", "Atribuir / Atributo", "/əˈtrɪbjuːt/",
     "She attributes her success to hard work and a little bit of luck.",
     "Ella atribuye su éxito al trabajo duro y a un poco de suerte.",
     ["Patience is one of the most valuable attributes a teacher can have.",
      "This poem is usually attributed to the fourteenth-century poet Dante.",
      "Researchers attribute the rise in allergies to modern air pollution."]),
    ("Beneficial", "Beneficioso / Valioso", "/ˌbɛnɪˈfɪʃəl/",
     "Regular moderate exercise is highly beneficial to cardiovascular health.",
     "El ejercicio moderado regular es altamente beneficioso para la salud cardiovascular.",
     ["The new trade agreement will be mutually beneficial for both countries.",
      "Some insects are actually beneficial to gardens and agriculture.",
      "A peaceful environment is beneficial to concentration and productivity."]),
    ("Capacity", "Capacidad / Aforo", "/kəˈpæsəti/",
     "The stadium has a seating capacity of approximately eighty thousand people.",
     "El estadio tiene una capacidad de asientos de aproximadamente ochenta mil personas.",
     ["She has an incredible capacity for remembering people's names and faces.",
      "The battery capacity of this new smartphone is twice the previous model.",
      "I have no capacity to take on any more work this month, I'm sorry."]),
    ("Category", "Categoría / Clase", "/ˈkætəɡɔːri/",
     "Products are organized by category to make browsing easier for customers.",
     "Los productos están organizados por categoría para facilitar la navegación a los clientes.",
     ["Books about cooking fall under the home and lifestyle category.",
      "This novel doesn't really fit neatly into any literary category.",
      "Winners are chosen in five different categories by a professional jury."]),
    ("Challenge", "Desafío / Reto", "/ˈtʃælɪndʒ/",
     "Climbing that mountain in winter was the greatest challenge of my whole life.",
     "Escalar esa montaña en invierno fue el mayor desafío de toda mi vida.",
     ["Nothing worthwhile is ever achieved without facing serious challenges.",
      "His theory seriously challenged all established scientific beliefs.",
      "The job will really challenge you and help you grow professionally."]),
    ("Circumstance", "Circunstancia / Situación", "/ˈsɜːrkəmstæns/",
     "Under no circumstances should you open the door to complete strangers.",
     "Bajo ninguna circunstancia debes abrirle la puerta a desconocidos.",
     ["Given the difficult circumstances, she handled the crisis remarkably well.",
      "A series of unfortunate circumstances ruined our carefully planned holiday.",
      "Circumstances permitting, we'd like to visit again sometime next spring."]),
    ("Coincide", "Coincidir", "/ˌkoʊɪnˈsaɪd/",
     "Our wedding anniversary happens to coincide with Valentine's Day.",
     "Nuestro aniversario de bodas coincide casualmente con el Día de San Valentín.",
     ["His tastes in music almost perfectly coincide with mine.",
      "The strike coincided with the busiest shopping weekend of the year.",
      "The two clocks always coincide exactly at noon every single day."]),
    ("Commitment", "Compromiso / Dedicación", "/kəˈmɪtmənt/",
     "Marriage requires a lifelong commitment from both people involved.",
     "El matrimonio requiere un compromiso de por vida de ambas personas involucradas.",
     ["We reaffirmed our commitment to protecting the natural environment.",
      "Her commitment to the project never wavered, even in the hardest times.",
      "You can't expect to learn a language without real personal commitment."]),
    ("Comparable", "Comparable / Semejante", "/ˈkɒmpərəbəl/",
     "No other painter of his time produced work comparable to Van Gogh.",
     "Ningún otro pintor de su época produjo obras comparables a las de Van Gogh.",
     ["The two apartments are of comparable size but vastly different prices.",
      "His achievements are comparable with the very best in the entire field.",
      "We need a comparable figure from last year for an accurate comparison."]),
    ("Compensate", "Compensar / Indemnizar", "/ˈkɒmpɛnseɪt/",
     "The company will compensate you for any work-related travel expenses.",
     "La empresa te compensará por cualquier gasto de viaje relacionado con el trabajo.",
     ["Nothing on earth can compensate for the loss of a beloved child.",
      "He tried to compensate for his lateness by bringing her some flowers.",
      "The factory workers were generously compensated for working overtime."]),
    ("Competence", "Competencia / Capacidad", "/ˈkɒmpɪtəns/",
     "The job interview is designed to assess your professional competence.",
     "La entrevista de trabajo está diseñada para evaluar tu competencia profesional.",
     ["She demonstrated great technical competence throughout the entire project.",
      "Competence and honesty are the two traits I value most in employees.",
      "Her competence as a surgeon is widely acknowledged across the country."]),
    ("Consequence", "Consecuencia / Resultado", "/ˈkɒnsɪkwəns/",
     "Every decision you make will have long-term consequences for your future.",
     "Cada decisión que tomes tendrá consecuencias a largo plazo para tu futuro.",
     ["He broke the law and now must face the serious consequences of his actions.",
      "One consequence of globalization is the rapid spread of infectious diseases.",
      "The accident was the direct consequence of reckless and irresponsible driving."]),
    ("Considerable", "Considerable / Importante", "/kənˈsɪdərəbəl/",
     "The project required a considerable investment of both time and money.",
     "El proyecto requirió una inversión considerable tanto de tiempo como de dinero.",
     ["There's been a considerable improvement in your English since last year.",
      "Considerable damage was caused by the unexpected hurricane last week.",
      "She has considerable influence over the board members' final decisions."]),
    ("Consistent", "Coherente / Constante", "/kənˈsɪstənt/",
     "He's one of our most consistent players, rarely performing below his level.",
     "Es uno de nuestros jugadores más constantes, rara vez rinde por debajo de su nivel.",
     ["Your theory needs to be consistent with all the known experimental facts.",
      "The quality of their products has remained consistently high for decades.",
      "Be consistent in your parenting rules or children will get confused."]),
    ("Constitute", "Constituir / Representar", "/ˈkɒnstɪtjuːt/",
     "Women constitute roughly fifty percent of the country's total population.",
     "Las mujeres constituyen aproximadamente el cincuenta por ciento de la población total del país.",
     ["Failing to appear in court will constitute a breach of your bail conditions.",
      "These twelve stories constitute the author's finest literary achievement.",
      "What constitutes a good life remains an open philosophical question."]),
    ("Contemplate", "Contemplar / Reflexionar", "/ˈkɒntəmpleɪt/",
     "She stood by the window, contemplating the snow falling on the rooftops.",
     "Ella se quedó junto a la ventana, contemplando la nieve caer sobre los tejados.",
     ["For a moment I seriously contemplated quitting and returning home.",
      "The ancient Greeks contemplated the nature of virtue and justice.",
      "We are still contemplating whether to accept their generous offer or not."]),
    ("Contribute", "Contribuir / Aportar", "/kənˈtrɪbjuːt/",
     "Everyone is expected to contribute something to the community project.",
     "Se espera que todos contribuyan en algo al proyecto comunitario.",
     ["Regular exercise and good diet contribute to long-term overall health.",
      "He contributed three major articles to the prestigious scientific journal.",
      "Multiple factors contributed to the dramatic collapse of the stock market."]),
    ("Convince", "Convencer / Persuadir", "/kənˈvɪns/",
     "She finally convinced me that joining the team was the right decision.",
     "Ella finalmente me convenció de que unirme al equipo era la decisión correcta.",
     ["How do you plan to convince them of the proposal's actual merits?",
      "I'm not convinced that this new marketing strategy will actually work.",
      "The evidence was overwhelming and convinced even the harshest critics."]),
    ("Correspond", "Corresponder / Coincidir", "/ˌkɒrɪˈspɒnd/",
     "The numbered buttons correspond to the chapters of the online video course.",
     "Los botones numerados corresponden a los capítulos del curso de video en línea.",
     ["The name on the envelope doesn't correspond with the name on the door.",
      "She still corresponds regularly with a pen-pal she met at age twelve.",
      "His version of events roughly corresponds with the available evidence."]),
    ("Crucial", "Crucial / Decisivo", "/ˈkruːʃəl/",
     "It's absolutely crucial that we reach an agreement before the deadline expires.",
     "Es absolutamente crucial que lleguemos a un acuerdo antes de que expire el plazo.",
     ["Trust plays a crucial role in every healthy long-term romantic relationship.",
      "The witness's testimony proved crucial to securing the final conviction.",
      "Tomorrow's match is crucial — if we lose, we're definitely out of the tournament."]),
    ("Cultivate", "Cultivar / Desarrollar", "/ˈkʌltɪveɪt/",
     "He worked hard to cultivate a reputation as a serious reliable professional.",
     "Él trabajó duro para cultivar una reputación de profesional serio y fiable.",
     ["The villagers cultivate rice and corn in the fertile valley below the mountains.",
      "Cultivate good study habits early and you'll never regret it later in life.",
      "She deliberately cultivated friendships with the most influential people around."]),
    ("Decline", "Declive / Rechazar", "/dɪˈklaɪn/",
     "There's been a steady decline in the population of this rural town.",
     "Ha habido un declive constante en la población de este pueblo rural.",
     ["I politely declined their dinner invitation because I already had plans.",
      "Sales of that product have declined sharply over the past three fiscal quarters.",
      "Her health began to decline rapidly after she turned eighty-five years old."]),
    ("Demonstrate", "Demostrar / Manifestar", "/ˈdɛmənstreɪt/",
     "The professor used a simple experiment to demonstrate the law of gravity.",
     "El profesor usó un experimento simple para demostrar la ley de la gravedad.",
     ["She consistently demonstrates extraordinary ability under extreme pressure.",
      "Thousands marched to demonstrate against the new proposed legislation.",
      "Please demonstrate how the new software application works to the class."]),
    ("Determined", "Decidido / Resuelto", "/dɪˈtɜːrmɪnd/",
     "She was absolutely determined to finish the marathon no matter what happened.",
     "Ella estaba absolutamente decidida a terminar el maratón sin importar lo que pasara.",
     ["We are determined to find a peaceful diplomatic solution to the conflict.",
      "His determined expression told me he wouldn't take no for an answer.",
      "Against all odds, a determined small group of soldiers held their ground."]),
    ("Develop", "Desarrollar / Elaborar", "/dɪˈvɛləp/",
     "The company will develop a brand new line of eco-friendly cleaning products.",
     "La empresa desarrollará una línea completamente nueva de productos de limpieza ecológicos.",
     ["Most babies develop their first words between twelve and eighteen months.",
      "She developed a serious interest in photography during her teenage years.",
      "Scientists are developing new treatments for previously incurable diseases."]),
    ("Diminish", "Disminuir / Reducir", "/dɪˈmɪnɪʃ/",
     "The effects of the drug gradually diminish after a few hours have passed.",
     "Los efectos del fármaco disminuyen gradualmente después de pasar unas horas.",
     ["Nothing could diminish her joy when she finally held her newborn baby.",
      "Our resources have diminished significantly since the last financial quarter.",
      "You should never diminish other people's achievements out of simple envy."]),
    ("Discipline", "Disciplina / Disciplinar", "/ˈdɪsəplɪn/",
     "Learning any musical instrument requires years of practice and strict discipline.",
     "Aprender cualquier instrumento musical requiere años de práctica y disciplina estricta.",
     ["Parents sometimes have to discipline children so they learn right from wrong.",
      "Yoga helps improve both physical discipline and deep mental concentration.",
      "His commanding officer disciplined him severely for breaking the military rules."]),
    ("Distinct", "Distinto / Diferente", "/dɪˈstɪŋkt/",
     "The two species have very distinct characteristics that set them clearly apart.",
     "Las dos especies tienen características muy distintas que las separan claramente.",
     ["There's a distinct smell of freshly baked bread coming from the kitchen.",
      "Her voice is so distinct I can recognize her on the phone instantly.",
      "We identified three distinct problems requiring three completely separate solutions."]),
    ("Dramatic", "Dramático / Espectacular", "/drəˈmætɪk/",
     "The new policy resulted in a dramatic decrease in highway traffic accidents.",
     "La nueva política resultó en una disminución dramática en los accidentes de tráfico en autopistas.",
     ["She gave a dramatic performance that moved the entire audience to tears.",
      "There's been a dramatic improvement in relations between the two countries.",
      "The coastline changes in the most dramatic way at sunset every evening."]),
    ("Duration", "Duración / Periodo", "/djʊˈreɪʃən/",
     "You can adjust the duration of the cooking process on this modern appliance.",
     "Puedes ajustar la duración del proceso de cocción en este moderno aparato.",
     ["For the duration of the crisis, all border crossings will remain closed.",
      "The total duration of the flight was exactly eleven hours and thirty minutes.",
      "Courses vary in duration from a single weekend to an entire academic semester."]),
    ("Elaborate", "Elaborado / Detallar", "/ɪˈlæbərət/",
     "They came up with a truly elaborate plan to stage the perfect surprise party.",
     "Idearon un plan verdaderamente elaborado para organizar la fiesta sorpresa perfecta.",
     ["Could you elaborate a little more on your earlier interesting statement?",
      "The wedding reception featured the most elaborate floral decorations I'd ever seen.",
      "She elaborated on the main points of her proposal during the meeting."]),
    ("Eliminate", "Eliminar / Suprimir", "/ɪˈlɪmɪneɪt/",
     "The new highway should eliminate most of the traffic congestion downtown.",
     "La nueva autopista debería eliminar la mayor parte de la congestión de tráfico en el centro.",
     ["The team was eliminated from the competition after a humiliating 4-0 defeat.",
      "We've managed to eliminate almost all errors from the production process.",
      "Certain pesticides are being eliminated because of their damaging environmental impact."]),
    ("Emphasize", "Enfatizar / Destacar", "/ˈɛmfəsaɪz/",
     "During the speech, he emphasized the importance of protecting human rights.",
     "Durante el discurso, enfatizó la importancia de proteger los derechos humanos.",
     ["I must emphasize that none of these changes will affect existing customers.",
      "Parents should emphasize effort over grades when talking to their children.",
      "The report emphasizes the need for increased investment in renewable energies."]),
    ("Encounter", "Encontrarse / Encuentro", "/ɪnˈkaʊntər/",
     "During our trip we encountered a family of wild bears in the deep forest.",
     "Durante nuestro viaje nos encontramos con una familia de osos salvajes en el bosque profundo.",
     ["I had a very strange encounter with an old acquaintance at the airport.",
      "This model successfully handles most problems users might commonly encounter.",
      "She encountered serious opposition from senior executives when she proposed the idea."]),
    ("Endeavor", "Esfuerzo / Empeñarse", "/ɪnˈdɛvər/",
     "Despite our best endeavors, we failed to reach the summit before nightfall.",
     "A pesar de nuestros mejores esfuerzos, no logramos llegar a la cima antes del anochecer.",
     ["We shall always endeavor to provide our customers with the highest quality service.",
      "His endeavors to learn Chinese were rewarded when he got the Beijing job.",
      "Learning a new skill worth having is always a worthy human endeavor."]),
    ("Enhance", "Mejorar / Aumentar", "/ɪnˈhæns/",
     "The chef added just a pinch of salt to enhance the delicate natural flavors.",
     "El chef añadió solo una pizca de sal para realzar los delicados sabores naturales.",
     ["Good lighting can dramatically enhance the appearance of any living room.",
      "Her new glasses slightly enhance her natural beauty and suit her well.",
      "Using visual aids will enhance your presentation and make it more engaging."]),
    ("Establish", "Establecer / Fundar", "/ɪˈstæblɪʃ/",
     "The university was originally established as a small theological college in 1683.",
     "La universidad fue fundada originalmente como un pequeño colegio teológico en 1683.",
     ["Let's establish some basic ground rules before we begin the actual negotiation.",
      "She quickly established herself as a leading expert in the emerging field.",
      "Police are still trying to establish the exact cause of the mysterious fire."]),
    ("Estimate", "Estimar / Cálculo", "/ˈɛstɪmeɪt/",
     "Economists estimate that inflation will fall below three percent by next year.",
     "Los economistas estiman que la inflación caerá por debajo del tres por ciento el próximo año.",
     ["The official total attendance figure is currently only a rough estimate.",
      "Can you give me a ballpark estimate for repairing the damage to my car?",
      "At a conservative estimate, the painting is worth at least two million dollars."]),
    ("Evaluate", "Evaluar / Valorar", "/ɪˈvæljueɪt/",
     "Every six months the manager meets with staff to evaluate their job performance.",
     "Cada seis meses el gerente se reúne con el personal para evaluar su desempeño laboral.",
     ["We need to carefully evaluate all the risks before making the final decision.",
      "Teachers evaluate students using a variety of different assessment methods.",
      "The research study evaluated the long-term effects of the controversial drug."]),
    ("Eventual", "Eventual / Final", "/ɪˈvɛntʃuəl/",
     "Hard work and perseverance led to his eventual success in the legal profession.",
     "El trabajo duro y la perseverancia condujeron a su eventual éxito en la profesión legal.",
     ["We're prepared for the eventual collapse of the old unstable bridge.",
      "Her eventual disappearance from public life remains shrouded in mystery even today.",
      "The argument between the two friends led to an eventual and sad reconciliation."]),
    ("Evolve", "Evolucionar / Desarrollarse", "/ɪˈvɒlv/",
     "Species evolve over thousands of generations through the mechanism of natural selection.",
     "Las especies evolucionan a lo largo de miles de generaciones a través del mecanismo de la selección natural.",
     ["The small family business eventually evolved into a major multinational corporation.",
      "Human language has evolved continuously over tens of thousands of years.",
      "Their business relationship slowly evolved into a deep personal friendship."]),
    ("Exaggerate", "Exagerar / Aumentar", "/ɪɡˈzædʒəreɪt/",
     "Don't exaggerate — it wasn't really as bad as you're making it sound now.",
     "No exageres — no fue tan malo como lo estás haciendo parecer ahora.",
     ["Fishermen are famously known to exaggerate the size of the fish they caught.",
      "The seriousness of the situation should not be exaggerated under any circumstances.",
      "Advertising often exaggerates the benefits of the products it is trying to sell."]),
    ("Expand", "Expandir / Ampliar", "/ɪkˈspænd/",
     "The company plans to expand its operations into at least three new Asian markets.",
     "La empresa planea expandir sus operaciones a al menos tres nuevos mercados asiáticos.",
     ["Metals expand when heated and contract again when they cool down.",
      "We should expand on this idea and explore all its practical applications.",
      "The universe has been expanding continuously since the moment of the Big Bang."]),
    ("Explicit", "Explícito / Claro", "/ɪkˈsplɪsɪt/",
     "The contract is quite explicit about what happens if you cancel the service.",
     "El contrato es bastante explícito sobre qué sucede si cancelas el servicio.",
     ["She gave me very explicit directions to the restaurant so I wouldn't get lost.",
      "We received explicit instructions not to discuss the matter with any reporters.",
      "The film contains some explicit scenes that make it unsuitable for young children."]),
    ("Explore", "Explorar / Investigar", "/ɪkˈsplɔːr/",
     "Early explorers set out in wooden ships to explore the unknown vast oceans.",
     "Los primeros exploradores partieron en barcos de madera para explorar los vastos océanos desconocidos.",
     ["We should explore every possible alternative before making this big commitment.",
      "Children naturally love to explore the world around them with all their senses.",
      "The research explores the relationship between stress and serious physical illness."]),
    ("Expose", "Exponer / Revelar", "/ɪkˈspoʊz/",
     "The brave journalist's articles managed to expose widespread official corruption.",
     "Los artículos del valiente periodista lograron exponer la corrupción oficial generalizada.",
     ["Don't expose your bare skin to the strong midday sun for too long.",
      "The documentary series exposed the terrible conditions inside the factory.",
      "As a young diplomat he was exposed to many different cultures and languages."]),
    ("Extract", "Extraer / Sacar", "/ɪkˈstrækt/",
     "The dentist had to extract one of my wisdom teeth because it was badly infected.",
     "El dentista tuvo que extraerme una muela del juicio porque estaba muy infectada.",
     ["The new recipe uses only ingredients extracted from purely natural organic sources.",
      "It took hours for detectives to extract the full truth from the reluctant witness.",
      "The machine is able to extract enough drinking water from atmospheric humidity."]),
    ("Fundamental", "Fundamental / Básico", "/ˌfʌndəˈmɛntəl/",
     "Freedom of expression is a fundamental human right that must never be compromised.",
     "La libertad de expresión es un derecho humano fundamental que nunca debe comprometerse.",
     ["There's a fundamental difference between being alone and actually feeling lonely.",
      "This discovery challenges the fundamental assumptions of modern physics.",
      "Reading and writing are two fundamental skills every child must master early on."]),
    ("Generate", "Generar / Producir", "/ˈdʒɛnəreɪt/",
     "The huge wind farm generates enough electricity to power fifty thousand homes.",
     "El enorme parque eólico genera suficiente electricidad para abastecer a cincuenta mil hogares.",
     ["His controversial speech generated a lot of heated debate throughout the media.",
      "We need to come up with new ways to generate additional revenue streams.",
      "The idea for the novel was generated by a strange dream the author had years ago."]),
    ("Genuine", "Genuino / Auténtico", "/ˈdʒɛnjuɪn/",
     "She showed genuine concern when she heard about my serious health problems.",
     "Ella mostró una preocupación genuina cuando se enteró de mis graves problemas de salud.",
     ["The painting was certified as a genuine work by the famous Dutch master Rembrandt.",
      "He greeted me with a genuine smile that immediately put me at my ease.",
      "Nobody doubts the genuine sincerity of his heartfelt humanitarian efforts."]),
    ("Gradual", "Gradual / Progresivo", "/ˈɡrædʒuəl/",
     "Learning a language is a gradual process that simply cannot be rushed.",
     "Aprender un idioma es un proceso gradual que simplemente no se puede apresurar.",
     ["There has been a gradual improvement in the patient's overall condition.",
      "The gradual shift towards renewable energy sources is finally gathering momentum.",
      "Aging is a gradual process that everyone must learn to accept gracefully."]),
    ("Hence", "Por lo tanto / De ahí", "/hɛns/",
     "He was out of the country; hence his unavoidable absence at the important meeting.",
     "Estaba fuera del país; de ahí su ausencia inevitable en la reunión importante.",
     ["It's extremely old and fragile, hence the need for very careful handling.",
      "All flights were canceled; hence we had no choice but to take the overnight train.",
      "The town was built near a river, hence its original name of Riverside."]),
    ("Hypothesis", "Hipótesis / Suposición", "/haɪˈpɒθəsɪs/",
     "The researchers proposed a new hypothesis to explain the previously unexplained phenomenon.",
     "Los investigadores propusieron una nueva hipótesis para explicar el fenómeno antes inexplicable.",
     ["Scientists design carefully controlled experiments to test their hypotheses.",
      "At this stage it's still only a hypothesis that requires further solid evidence.",
      "His initial hypothesis turned out to be remarkably accurate despite little data."]),
    ("Identify", "Identificar / Reconocer", "/aɪˈdɛntɪfaɪ/",
     "Witnesses were asked to identify the suspect from a police lineup of six men.",
     "Se pidió a los testigos que identificaran al sospechoso de una rueda de reconocimiento policial de seis hombres.",
     ["We first need to identify the underlying cause of the recurring failures.",
      "The body was badly decomposed, making it impossible to identify visually.",
      "She identified strongly with the main character in the powerful novel."]),
    ("Ignore", "Ignorar / Hacer caso omiso", "/ɪɡˈnɔːr/",
     "For your own safety, never ignore official weather warnings during severe storms.",
     "Por tu propia seguridad, nunca ignores las advertencias meteorológicas oficiales durante tormentas severas.",
     ["He chose to ignore all my friendly advice and then bitterly regretted it.",
      "You can't just ignore the problem and hope it will magically disappear by itself.",
      "She politely ignored his rude comment and continued with her fascinating presentation."]),
    ("Implement", "Implementar / Poner en práctica", "/ˈɪmplɪment/",
     "It's one thing to propose a new plan, but quite another to actually implement it.",
     "Una cosa es proponer un plan nuevo y muy distinta es implementarlo realmente.",
     ["The government will implement the new healthcare reform starting next January.",
      "We decided to implement the committee's recommendations in full and without delay.",
      "The company implemented strict new security measures after the major data breach."]),
    ("Implication", "Implicación / Consecuencia", "/ˌɪmplɪˈkeɪʃən/",
     "The full implications of the court ruling won't be known for several years.",
     "Las implicaciones completas de la sentencia judicial no se conocerán hasta dentro de varios años.",
     ["Have you considered all the financial implications of buying such an expensive house?",
      "The implication of his statement was that he considered us all partly responsible.",
      "Researchers are studying the broader implications of this new scientific discovery."]),
    ("Imply", "Implicar / Dar a entender", "/ɪmˈplaɪ/",
     "Are you implying that I somehow knew about the scandal in advance?",
     "¿Estás implicando que de alguna manera sabía yo del escándalo con antelación?",
     ["A positive diagnosis does not necessarily imply that all treatment options are useless.",
      "His silence seemed to imply that he agreed with the criticism against him.",
      "The new regulations imply major changes for every small business in the country."]),
    ("Incorporate", "Incorporar / Incluir", "/ɪnˈkɔːrpəreɪt/",
     "The revised design will incorporate all the suggestions from the client feedback.",
     "El diseño revisado incorporará todas las sugerencias de los comentarios del cliente.",
     ["Her paintings beautifully incorporate elements from both Eastern and Western traditions.",
      "We decided to incorporate the small business to limit our personal legal liability.",
      "Try to incorporate more fresh vegetables into your regular daily diet."]),
    ("Indicate", "Indicar / Señalar", "/ˈɪndɪkeɪt/",
     "The latest statistics indicate a gradual but steady economic recovery is underway.",
     "Las últimas estadísticas indican que una recuperación económica gradual pero constante está en marcha.",
     ["Please indicate your preferred method of payment on the order form below.",
      "Research clearly indicates that smoking dramatically increases cancer risk.",
      "The arrow on the map indicates where the famous historical battle took place."]),
    ("Inevitable", "Inevitable / Seguro", "/ɪnˈɛvɪtəbəl/",
     "Change is inevitable in life, so one must learn to adapt and embrace it.",
     "El cambio es inevitable en la vida, así que hay que aprender a adaptarse y aceptarlo.",
     ["A clash between the two great armies seemed sadly inevitable at that point.",
      "Failure is an inevitable part of any worthwhile journey towards true success.",
      "With the heavy rain forecast, floods in the valley area are now virtually inevitable."]),
    ("Influence", "Influencia / Influenciar", "/ˈɪnfluəns/",
     "Teachers have a profound long-term influence on the future lives of their students.",
     "Los profesores tienen una profunda influencia a largo plazo en la vida futura de sus alumnos.",
     ["Don't let peer pressure influence you into doing something you know is wrong.",
      "Her mother was the single biggest creative influence in her entire life.",
      "Many psychologists study how advertising influences consumer purchasing decisions."]),
    ("Inherit", "Heredar / Recibir", "/ɪnˈhɛrɪt/",
     "The children will inherit the family estate when both parents eventually pass away.",
     "Los hijos heredarán la finca familiar cuando ambos padres fallezcan eventualmente.",
     ["She inherited her grandmother's beautiful curly red hair and sparkling green eyes.",
      "The new government inherited an economy in ruins after a decade of mismanagement.",
      "Humans inherit half of their genetic material from each biological parent."]),
    ("Initiate", "Iniciar / Empezar", "/ɪˈnɪʃieɪt/",
     "The United Nations hoped to initiate peace talks between the warring factions.",
     "Las Naciones Unidas esperaban iniciar conversaciones de paz entre las facciones en guerra.",
     ["Anyone wishing to join the club must first initiate the membership application process.",
      "She initiated a very ambitious fundraising campaign for the local children's hospital.",
      "The male bird initiates an elaborate courtship ritual to attract a suitable mate."]),
    ("Innovative", "Innovador / Vanguardsista", "/ˈɪnəveɪtɪv/",
     "The young engineer won many awards for his innovative engineering designs.",
     "El joven ingeniero ganó muchos premios por sus diseños de ingeniería innovadores.",
     ["They are widely recognized as the most innovative company in the entire tech industry.",
      "We need a truly innovative solution — not more of the same old unsuccessful ideas.",
      "His innovative teaching methods transformed the school into a national success story."]),
    ("Insight", "Perspicacia / Visión", "/ˈɪnsaɪt/",
     "The documentary offers fascinating insight into the private life of the famous artist.",
     "El documental ofrece una visión fascinante sobre la vida privada del famoso artista.",
     ["She had a sudden brilliant insight that immediately solved the long-standing puzzle.",
      "The book provides valuable insights into the psychology of human relationships.",
      "His years of experience in the field give him unique insights into market trends."]),
    ("Integrate", "Integrar / Incorporar", "/ˈɪntɪɡreɪt/",
     "It takes time for recent immigrants to integrate fully into their new host society.",
     "Los inmigrantes recientes tardan tiempo en integrarse plenamente en su nueva sociedad de acogida.",
     ["The new software integrates perfectly with all your existing business applications.",
      "Schools must integrate children with special needs into regular classrooms whenever possible.",
      "The design integrates classical architecture with the most modern eco-friendly materials."]),
    ("Intense", "Intenso / Fuerte", "/ɪnˈtɛns/",
     "The intense heat of the midday desert sun was almost unbearable for the travelers.",
     "El intenso calor del sol del mediodía en el desierto era casi insoportable para los viajeros.",
     ["There was intense competition between the two rival teams throughout the entire match.",
      "She felt intense relief when the long difficult surgery was finally declared a success.",
      "Intense military training builds both enormous physical strength and mental resilience."]),
    ("Interact", "Interactuar / Relacionarse", "/ˌɪntərˈækt/",
     "Children learn social skills by interacting with other children at school.",
     "Los niños aprenden habilidades sociales interactuando con otros niños en la escuela.",
     ["These two chemicals interact in surprising ways at very high temperatures.",
      "The professor enjoys interacting directly with students outside formal classroom hours.",
      "Modern smartphones allow users to interact with the entire world instantly."]),
    ("Interpret", "Interpretar / Explicar", "/ɪnˈtɜːrprɪt/",
     "The poet's work has been interpreted in many different ways by literary critics.",
     "La obra del poeta ha sido interpretada de muchas maneras diferentes por los críticos literarios.",
     ["She was hired to interpret for the foreign delegates during the international summit.",
      "How should we interpret these latest, somewhat confusing experimental results?",
      "The dream can be interpreted as a symbol of your hidden fears and desires."]),
    ("Investigate", "Investigar / Indagar", "/ɪnˈvɛstɪɡeɪt/",
     "Police are currently investigating the suspicious disappearance of the wealthy businessman.",
     "La policía está investigando actualmente la sospechosa desaparición del rico empresario.",
     ["The committee was formed to investigate allegations of fraud against senior officials.",
      "Scientists have been investigating the mysterious phenomenon for over twenty years.",
      "Journalists are usually the first to investigate and uncover cases of political corruption."]),
    ("Maintain", "Mantener / Sostener", "/meɪnˈteɪn/",
     "The highways are maintained regularly throughout the year to guarantee road safety.",
     "Las autopistas se mantienen regularmente durante todo el año para garantizar la seguridad vial.",
     ["She maintains a strict vegetarian diet for both health and ethical reasons.",
      "The hotel has maintained its reputation for excellence for more than a century.",
      "Despite the many accusations, he has always maintained his complete innocence."]),
    ("Manipulate", "Manipular / Manejar", "/məˈnɪpjuleɪt/",
     "The data had been deliberately manipulated to support a predetermined conclusion.",
     "Los datos habían sido manipulados deliberadamente para apoyar una conclusión predeterminada.",
     ["Advertising is designed to manipulate consumer emotions to encourage purchases.",
      "Machinery of this complexity must be manipulated only by well-trained technicians.",
      "He is a charismatic leader who knows how to manipulate crowds of followers."]),
    ("Motivate", "Motivar / Estimular", "/ˈmoʊtɪveɪt/",
     "Great leaders are able to motivate their teams to achieve things they never thought possible.",
     "Los grandes líderes son capaces de motivar a sus equipos para lograr cosas que nunca pensaron posibles.",
     ["What motivated you to suddenly give up a well-paid corporate career and become an artist?",
      "Good teachers motivate their students by showing genuine enthusiasm for the subject matter.",
      "Our employees are motivated by a combination of fair pay, recognition and personal challenge."]),
    ("Negotiate", "Negociar / Tratar", "/nɪˈɡoʊʃieɪt/",
     "Union representatives will negotiate better working conditions with the company management.",
     "Los representantes sindicales negociarán mejores condiciones laborales con la dirección de la empresa.",
     ["They are currently negotiating a peace treaty to end the war that has lasted five years.",
      "The driver skillfully negotiated the sharp icy turns of the dangerous mountain road.",
      "You can usually negotiate the price of furniture at this kind of family-run store."]),
    ("Nevertheless", "No obstante / Sin embargo", "/ˌnɛvərðəˈlɛs/",
     "The task was extremely difficult; nevertheless, the team somehow finished on schedule.",
     "La tarea fue sumamente difícil; no obstante, el equipo de alguna manera terminó a tiempo.",
     ["The news came as a terrible shock. Nevertheless, we knew we had to keep going forward.",
      "He's quiet and shy. Nevertheless, he gives among the most memorable speeches I've ever heard.",
      "The storm was terrible. Nevertheless, our small boat made it safely back to the harbor."]),
    ("Obtain", "Obtener / Conseguir", "/əbˈteɪn/",
     "You must obtain a valid work permit before you can legally accept employment in the country.",
     "Debes obtener un permiso de trabajo válido antes de poder aceptar legalmente un empleo en el país.",
     ["He obtained a copy of the original document from the national archives in Madrid.",
      "Scientists are hoping to obtain new information from the powerful space telescope's latest images.",
      "She obtained outstanding exam results and was accepted by every university she applied to."]),
    ("Obvious", "Obvio / Evidente", "/ˈɒbviəs/",
     "It was obvious from the very beginning that the whole proposal was completely impractical.",
     "Era obvio desde el principio que toda la propuesta era completamente impráctica.",
     ["The answer seems so obvious to me that I'm genuinely surprised nobody thought of it before.",
      "For some reason that isn't obvious to me, she refused to speak to me at the party.",
      "There's an almost obvious connection between smoking tobacco and certain serious lung diseases."]),
    ("Occupy", "Ocupar / Invadir", "/ˈɒkjupaɪ/",
     "The new enormous office building occupies an entire city block downtown.",
     "El nuevo edificio de oficinas enorme ocupa una manzana entera en el centro.",
     ["Work occupies most of my time during the week, leaving little for hobbies.",
      "A large portion of the country was still under enemy military occupation.",
      "Reading occupies every free moment of her busy but very satisfying life."]),
    ("Ongoing", "En curso / Continuo", "/ˈɒnɡoʊɪŋ/",
     "The ongoing investigation into the scandal is not expected to conclude until next spring.",
     "No se espera que la investigación en curso sobre el escándalo concluya hasta la próxima primavera.",
     ["We are in an ongoing process of continuous improvement of all our products.",
      "Support for the software is provided on an ongoing basis for the full warranty period.",
      "There's an ongoing debate among economists about the long-term effects of the new policy."]),
    ("Parallel", "Paralelo / Simultáneo", "/ˈpærəlɛl/",
     "The new road runs parallel to the old railway line for about forty kilometers.",
     "La nueva carretera discurre paralela a la antigua línea de ferrocarril durante unos cuarenta kilómetros.",
     ["The book draws interesting parallels between the two historical revolutions.",
      "The two companies are conducting parallel investigations into the same safety issue.",
      "The career paths of the two brothers followed strangely parallel trajectories for decades."]),
    ("Perceive", "Peribir / Percibir", "/pərˈsiːv/",
     "She perceived a note of hesitation in his voice when he answered the difficult question.",
     "Ella percibió un matiz de vacilación en su voz cuando respondió a la difícil pregunta.",
     ["The public generally perceives politicians as being dishonest and motivated mainly by self-interest.",
      "How the human brain actually perceives color is still only partially understood by neuroscientists.",
      "He perceived the opportunity almost before anyone else in the room had even noticed it."]),
    ("Persist", "Persistir / Durar", "/pərˈsɪst/",
     "If the symptoms persist for more than three days, you should definitely consult a qualified doctor.",
     "Si los síntomas persisten durante más de tres días, definitivamente deberías consultar a un médico cualificado.",
     ["Despite the failure of his early experiments, the determined inventor persisted in his research.",
      "The cold weather persisted well into what should have been the warm spring months.",
      "You must persist and keep trying until you eventually achieve what you have set out to do."]),
    ("Phenomenon", "Fenómeno / Hecho", "/fɪˈnɒmɪnən/",
     "The northern lights are one of the most beautiful natural phenomena on Earth.",
     "Las auroras boreales son uno de los fenómenos naturales más bellos de la Tierra.",
     ["Social media addiction is a relatively recent psychological phenomenon affecting millions.",
      "Scientists are still trying to fully explain the mysterious phenomenon of ball lightning.",
      "The Beatles were an unmatched cultural phenomenon that changed the history of popular music forever."]),
    ("Potential", "Potencial / Posible", "/pəˈtɛnʃəl/",
     "The project has enormous commercial potential if it's developed and marketed correctly.",
     "El proyecto tiene un enorme potencial comercial si se desarrolla y comercializa correctamente.",
     ["All children have hidden potential that simply needs to be discovered and nurtured by caring adults.",
      "What do you think is the long-term potential of this new medical treatment?",
      "The abandoned warehouse site has great potential for conversion into modern luxury loft apartments."]),
    ("Prejudice", "Prejuicio / Preconcepto", "/ˈprɛdʒədɪs/",
     "The speech delivered a powerful attack on racial prejudice and all forms of discrimination.",
     "El discurso lanzó un poderoso ataque contra el prejuicio racial y todas las formas de discriminación.",
     ["Nobody should be denied an equal opportunity simply on the grounds of outdated prejudice.",
      "Her experience of prejudice as a child motivated her to fight for human rights as an adult.",
      "We must all learn to judge each person as an individual and never act on prejudice."]),
    ("Preserve", "Preservar / Conservar", "/prɪˈzɜːrv/",
     "It's every generation's sacred duty to preserve the world's cultural heritage for the future.",
     "Es el deber sagrado de cada generación preservar el patrimonio cultural del mundo para el futuro.",
     ["Traditionally, salt was widely used to preserve food for long winters without refrigeration.",
      "The old national park was established to preserve the unique forest ecosystem forever.",
      "She recorded her grandmother's stories on video to preserve the family history for future generations."]),
    ("Prominent", "Destacado / Importante", "/ˈprɒmɪnənt/",
     "She's a prominent lawyer who has handled several extremely high-profile legal cases.",
     "Ella es una abogada destacada que ha llevado varios casos legales de altísimo perfil.",
     ["The newspaper's prominent front-page story forced the government to issue an official response.",
      "He occupies a very prominent position in the modern art world, curating major international exhibitions.",
      "The most prominent feature of the landscape is the large snow-covered volcano in the distance."]),
    ("Relevant", "Relevante / Pertinente", "/ˈrɛləvənt/",
     "Please limit your comments to matters that are directly relevant to the topic under discussion.",
     "Por favor limita tus comentarios a asuntos que sean directamente relevantes para el tema en discusión.",
     ["Some of his books are even more relevant today than they were when first published decades ago.",
      "Make sure you submit only work experience that is relevant to the specific position you are applying for.",
      "Court rules strictly prevent lawyers from introducing evidence that is not directly relevant to the case."]),
    ("Reluctant", "Renuente / Reacio", "/rɪˈlʌktənt/",
     "He was naturally reluctant to sell the beloved family home where his children had grown up.",
     "Naturalmente era reacio a vender la querida casa familiar donde sus hijos habían crecido.",
     ["She seemed reluctant at first, but eventually agreed to help us with the complicated task.",
      "Most people are reluctant to speak publicly about their own serious personal problems.",
      "The witness was reluctant to identify the attackers, apparently out of fear of possible retaliation."]),
    ("Require", "Requerir / Necesitar", "/rɪˈkwaɪər/",
     "All the jobs advertised require at least three years of relevant professional experience.",
     "Todos los empleos anunciados requieren al menos tres años de experiencia profesional relevante.",
     ["You will be required to present a valid form of photographic ID before entering the building.",
      "The extremely technical report requires a careful detailed reading before you can fully understand it.",
      "True mastery of any complex skill requires many thousands of hours of deliberate practice."]),
    ("Resignation", "Renuncia / Resignación", "/ˌrɛzɪɡˈneɪʃən/",
     "The chief executive's sudden resignation took the entire business community completely by surprise.",
     "La repentina renuncia del director general tomó a toda la comunidad empresarial por sorpresa.",
     ["Failing the final entrance exam was devastating, but she eventually accepted it with quiet resignation.",
      "I have no intention of submitting my resignation despite all the recent pressure on me to leave.",
      "Formal acceptance of the Minister's resignation will be officially announced by the palace later today."]),
    ("Restrict", "Restringir / Limitar", "/rɪˈstrɪkt/",
     "During the pandemic, governments severely restricted travel between international borders.",
     "Durante la pandemia, los gobiernos restringieron severamente los viajes entre fronteras internacionales.",
     ["The new law will restrict the amount of sugar that beverage manufacturers can add to soft drinks.",
      "Doctors strongly advise restricting salt intake for patients who suffer from high blood pressure.",
      "Membership of the exclusive club is strictly restricted to invited guests only."]),
    ("Significant", "Significativo / Importante", "/sɪɡˈnɪfɪkənt/",
     "The discovery of penicillin was one of the most significant medical breakthroughs in all human history.",
     "El descubrimiento de la penicilina fue uno de los avances médicos más significativos de toda la historia humana.",
     ["There's been a significant increase in sales since we launched the new advertising campaign.",
      "The results of the scientific study are statistically significant and cannot be dismissed lightly.",
      "The older generations made significant personal sacrifices so that we could live in freedom and peace."]),
    ("Subsequent", "Posterior / Siguiente", "/ˈsʌbsɪkwənt/",
     "The first experiment failed completely, but all subsequent attempts were remarkably successful.",
     "El primer experimento fracasó por completo, pero todos los intentos posteriores fueron notablemente exitosos.",
     ["Subsequent events completely validated the wisdom of the difficult initial decision.",
      "The lessons we learned in the initial training program were applied in all subsequent workshops.",
      "The economic downturn and the subsequent recession put thousands of people out of work."]),
    ("Substantial", "Sustancial / Importante", "/səbˈstænʃəl/",
     "The wealthy philanthropist made a substantial anonymous donation to children's medical research.",
     "El rico filántropo hizo una donación sustancial anónima para la investigación médica infantil.",
     ["A substantial majority of the population voted in favor of the proposed constitutional reform.",
      "We've made substantial progress on the ambitious project since the last time we met.",
      "They suffered substantial financial losses as a direct result of the sudden unexpected stock market crash."]),
    ("Sufficient", "Suficiente / Bastante", "/səˈfɪʃənt/",
     "The emergency food supplies were barely sufficient for the hundreds of families displaced by the hurricane.",
     "Los suministros alimentarios de emergencia apenas fueron suficientes para los cientos de familias desplazadas por el huracán.",
     ["You must have sufficient valid identification before they will issue you a new passport.",
      "A simple healthy diet combined with regular exercise is sufficient for most people to maintain good health.",
      "The evidence presented against the accused was simply not sufficient to secure a criminal conviction."]),
    ("Sustain", "Sostener / Mantener", "/səˈsteɪn/",
     "The plants sustained severe frost damage during the unusually cold winter temperatures.",
     "Las plantas sufrieron graves daños por las heladas durante las temperaturas invernales inusualmente frías.",
     ["The soil in this region is extremely fertile and can sustain more than two harvests every single year.",
      "He managed to sustain the very high level of performance throughout the entire long competition.",
      "Sustaining genuine long-term economic growth is the central challenge for every national government today."]),
    ("Temporary", "Temporal / Provisional", "/ˈtɛmpərɛri/",
     "The bridge is closed for temporary repairs but will reopen to traffic next Monday.",
     "El puente está cerrado por reparaciones temporales pero reabrirá al tráfico el próximo lunes.",
     ["The company hired a temporary replacement while the regular manager was away on extended sick leave.",
      "Most of the problems you're experiencing right now are only temporary and will soon pass.",
      "They found temporary accommodation in a refugee camp until more permanent housing could be arranged."]),
    ("Therefore", "Por lo tanto / En consecuencia", "/ˈðɛrfɔːr/",
     "He has not submitted any of the required coursework; therefore, he will almost certainly fail the course.",
     "No ha entregado ninguno de los trabajos requeridos; por lo tanto, casi con seguridad suspenderá la asignatura.",
     ["Neither side was prepared to compromise on the core issues. Therefore, the long peace talks finally collapsed completely.",
      "She has a proven track record of outstanding success. Therefore, we have full confidence that she will do an excellent job in the new role.",
      "The weather forecast warned of severe storms approaching the coast. Therefore, the decision was made to evacuate all low-lying villages immediately."]),
    ("Transition", "Transición / Cambio", "/trænˈzɪʃən/",
     "The transition from full-time work to peaceful retirement can be surprisingly difficult for many people.",
     "La transición del trabajo a tiempo completo a la jubilación pacífica puede ser sorprendentemente difícil para muchas personas.",
     ["The period of political transition following the dictator's fall was marked by widespread social unrest.",
      "We will support you through the transition period as you gradually take over the full responsibilities of the role.",
      "Adolescence is the often-turbulent transition from childhood to full emotional and physical adulthood."]),
    ("Ultimately", "En última instancia / Finalmente", "/ˈʌltɪmətli/",
     "All of life's seemingly endless struggles ultimately serve the purpose of making us stronger, wiser human beings.",
     "Todas las aparentemente infinitas luchas de la vida sirven en última instancia para hacernos seres humanos más fuertes y sabios.",
     ["However long and difficult the path may be, justice will ultimately prevail and the guilty will be fairly punished.",
      "Despite the intervention of many experts, it was ultimately the child's own mother who discovered the rare diagnosis.",
      "No matter who advises you in the end, you are ultimately responsible for every major decision you make in your life."]),
    ("Undergo", "Sufrir / Someterse a", "/ˌʌndərˈɡoʊ/",
     "The old downtown theater is currently undergoing extensive renovations to restore it to its former glory.",
     "El viejo teatro del centro está sometiéndose actualmente a renovaciones extensas para restaurarlo a su antiguo esplendor.",
     ["She had to undergo emergency heart surgery at only forty years of age, but has since made a full recovery.",
      "The entire nation is undergoing a profound social and economic transformation that will take at least a decade to complete.",
      "All recruits must undergo a grueling three-month military training program before they are considered active duty soldiers."]),
    ("Undertake", "Emprender / Encargarse de", "/ˌʌndərˈteɪk/",
     "The ambitious research project was undertaken by a multinational team of renowned scientists from twelve different universities.",
     "El ambicioso proyecto de investigación fue emprendido por un equipo multinacional de científicos renombrados de doce universidades diferentes.",
     ["We can only accept and undertake this complex assignment if we receive adequate financial resources and sufficient time to complete it thoroughly.",
      "She undertook the enormous personal challenge of walking the entire two thousand mile historic pilgrimage route alone, carrying all her supplies.",
      "The contractor has undertaken to finish all building works by the end of the calendar year, or face very heavy financial penalties under the contract terms."]),
    ("Validate", "Validar / Confirmar", "/ˈvælɪdeɪt/",
     "You will need to validate your email address by clicking on the automatic confirmation link sent to your inbox.",
     "Necesitarás validar tu dirección de correo electrónico haciendo clic en el enlace de confirmación automática enviado a tu bandeja de entrada.",
     ["The experimental results obtained independently by two separate research teams validated the original scientist's revolutionary theory.",
      "Just because so many people share your opinion does not automatically validate it or make it morally correct.",
      "The immigration officer will validate your travel documents before stamping your passport and allowing you into the country."]),
    ("Whereabouts", "Paradero / Rastros", "/ˈwɛrəbaʊts/",
     "The famous explorer's exact whereabouts after he vanished into the dense jungle in 1925 remain completely unknown.",
     "El paradero exacto del famoso explorador después de que desapareciera en la densa selva en 1925 sigue siendo completamente desconocido.",
     ["Nobody seems to have any reliable information as to the current whereabouts of the long-lost priceless medieval manuscript.",
      "Police are urgently appealing to the general public for any information about the mysterious whereabouts of the missing thirteen-year-old girl.",
      "Have you heard anything about the whereabouts of my old leather briefcase? I seem to have left it somewhere on the day of the conference."]),
    ("Widespread", "Generalizado / Extendido", "/ˈwaɪdsprɛd/",
     "The fall of the Berlin Wall was met with widespread public celebration and a tremendous sense of hope throughout all of Europe.",
     "La caída del Muro de Berlín se recibió con una celebración pública generalizada y una enorme sensación de esperanza en toda Europa.",
     ["Widespread flooding caused by the record-breaking heavy rainfall has destroyed thousands of homes across the entire river valley region.",
      "There is now widespread scientific acceptance that human industrial activity is the main driving force behind modern global climate change.",
      "Widespread public outrage followed the shocking revelation that senior politicians had been systematically lying to the electorate for decades."]),
]

common_cards = []
for i, (wen, wes, pron, ex, exes, extras) in enumerate(harder_common_words, 1):
    common_cards.append({
        "id": f"cw_{i}",
        "wordEn": wen,
        "wordEs": wes,
        "pronunciation": pron,
        "example": ex,
        "exampleEs": exes,
        "extraExamples": extras
    })

verb_tenses_raw = [
    ("Present Simple", "Presente Simple",
     "Subject + Verb (-s for he/she/it)",
     "I drink coffee every single morning before work.",
     "Bebo café todas las mañanas antes del trabajo.",
     ["She works in a hospital as a pediatric nurse.",
      "The sun rises in the east and sets in the west.",
      "They usually travel to Europe once every two years."]),
    ("Present Continuous", "Presente Continuo",
     "Subject + am/is/are + Verb-ing",
     "I am reading a very interesting book right now.",
     "Estoy leyendo un libro muy interesante ahora mismo.",
     ["She is cooking dinner in the kitchen for her family.",
      "We are building our own house in the countryside.",
      "They are currently discussing the new marketing strategy."]),
    ("Present Perfect", "Presente Perfecto",
     "Subject + have/has + Past Participle",
     "I have visited that beautiful country three times already.",
     "He visitado ese hermoso país tres veces ya.",
     ["She has already finished her master's degree thesis.",
      "We have lived in this neighborhood for fifteen years.",
      "He has never tried sushi in his entire life — would you believe it?"]),
    ("Present Perfect Continuous", "Presente Perfecto Continuo",
     "Subject + have/has + been + Verb-ing",
     "I have been studying English for almost six years now.",
     "He estado estudiando inglés durante casi seis años ya.",
     ["She has been working since six in the morning today.",
      "They have been building that bridge for over three years.",
      "We have been waiting here for more than an hour and a half."]),
    ("Past Simple", "Pasado Simple",
     "Subject + Past Verb",
     "I went to Paris with my family two summers ago.",
     "Fui a París con mi familia hace dos veranos.",
     ["She bought a new laptop for work last Friday afternoon.",
      "We saw a very sad movie at the cinema yesterday evening.",
      "They lived in Japan from 2015 until very recently."]),
    ("Past Continuous", "Pasado Continuo",
     "Subject + was/were + Verb-ing",
     "I was taking a shower when the phone suddenly rang.",
     "Estaba dándome una ducha cuando el teléfono sonó de repente.",
     ["She was studying while her brother was playing video games.",
      "They were walking in the park when it started to rain heavily.",
      "We were having a lovely dinner when the power went out suddenly."]),
    ("Past Perfect", "Pasado Perfecto",
     "Subject + had + Past Participle",
     "I had already eaten dinner when my friends arrived at my house.",
     "Ya había cenado cuando mis amigos llegaron a mi casa.",
     ["She had never tasted such delicious food before her trip to Italy.",
      "They had finished the project a week before the actual deadline.",
      "We realized we had been to that same place ten years earlier."]),
    ("Past Perfect Continuous", "Pasado Perfecto Continuo",
     "Subject + had + been + Verb-ing",
     "I had been working there for five years when they finally promoted me.",
     "Había estado trabajando allí durante cinco años cuando finalmente me ascendieron.",
     ["She had been waiting for over an hour when the taxi finally showed up.",
      "They had been traveling for twenty hours before they finally reached home.",
      "We had been searching for the keys for an hour when we found them."]),
    ("Future with Will", "Futuro con Will",
     "Subject + will + Verb",
     "I will call you as soon as I arrive at the airport tomorrow.",
     "Te llamaré en cuanto llegue al aeropuerto mañana.",
     ["She will probably be late because of all the traffic tonight.",
      "Don't worry — I will help you finish the report after lunch.",
      "They will announce the winner of the contest in five minutes."]),
    ("Be Going To", "Futuro con Going To",
     "Subject + am/is/are + going to + Verb",
     "I am going to learn how to play the guitar next year.",
     "Voy a aprender a tocar la guitarra el próximo año.",
     ["She is going to have a baby in about three months.",
      "We are going to move to a bigger apartment next summer.",
      "They are going to open a new restaurant downtown very soon."]),
    ("Future Continuous", "Futuro Continuo",
     "Subject + will + be + Verb-ing",
     "This time tomorrow I will be lying on a beach in Hawaii.",
     "A estas horas mañana estaré tirado en una playa en Hawái.",
     ["She will be giving an important presentation at ten o'clock.",
      "We will be driving through the mountains all day Saturday.",
      "This time next year they will be living in their brand new house."]),
    ("Future Perfect", "Futuro Perfecto",
     "Subject + will + have + Past Participle",
     "By the end of this year I will have finished my university degree.",
     "Para finales de este año habré terminado mi carrera universitaria.",
     ["By next month she will have worked here for exactly ten years.",
      "When you arrive, we will have already prepared everything for you.",
      "By 2030 they will have completed the entire construction project."]),
]

verb_tense_cards = []
for i, (wen, wes, struct, ex, exes, extras) in enumerate(verb_tenses_raw, 1):
    verb_tense_cards.append({
        "id": f"vt_{i}",
        "wordEn": wen,
        "wordEs": wes,
        "pronunciation": "",
        "example": ex,
        "exampleEs": exes,
        "extraExamples": extras,
        "structure": struct
    })

category_common = {
    "id": "common_words",
    "name": "Common Words",
    "nameEs": "Palabras comunes",
    "icon": "🔴",
    "color": "#EF5350",
    "cards": common_cards
}

category_tenses = {
    "id": "verb_tenses",
    "name": "Verb Tenses",
    "nameEs": "Tiempos verbales",
    "icon": "⏰",
    "color": "#AB47BC",
    "cards": verb_tense_cards
}

data["categories"].append(category_common)
data["categories"].append(category_tenses)

with open("assets/data/vocabulary.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"common_words cards: {len(common_cards)}")
print(f"verb_tenses cards: {len(verb_tense_cards)}")
